import os
import sqlite3
import re
import datetime

from itertools import chain

from ..Models import DatabaseManager as DB, yId

# for debugging
from pprint import pprint

################################################################################
################################################################################



statTypes = [{'abrv': 'Fum', 'stat_id': '3', 'title': 'Fumbles Lost'},
             {'abrv': 'PaComp', 'stat_id': '102', 'title': 'Completions'},
             {'abrv': 'PaAtt', 'stat_id': '103', 'title': 'Attempts'},
             {'abrv': 'PaYds', 'stat_id': '105', 'title': 'Yards'},
             {'abrv': 'PaTDs', 'stat_id': '108', 'title': 'Touchdowns'},
             {'abrv': 'PaInts', 'stat_id': '109', 'title': 'Interceptions'},
             {'abrv': 'PaSacks', 'stat_id': '111', 'title': 'Sacks'},
             {'abrv': 'SackYdsL', 'stat_id': '112', 'title': 'Yards Lost'},
             {'abrv': 'QBRat', 'stat_id': '113', 'title': 'QB Rating'},
             {'abrv': 'RuAtt', 'stat_id': '202', 'title': 'Rushes'},
             {'abrv': 'RuYds', 'stat_id': '203', 'title': 'Yards'},
             {'abrv': 'RuTDs', 'stat_id': '207', 'title': 'Touchdowns'},
             {'abrv': 'Rec', 'stat_id': '302', 'title': 'Receptions'},
             {'abrv': 'RecYds', 'stat_id': '303', 'title': 'Yards'},
             {'abrv': 'RecTDs', 'stat_id': '309', 'title': 'Touchdowns'},
             {'abrv': 'Tgt', 'stat_id': '310', 'title': 'Targets'},
             {'abrv': 'FGM', 'stat_id': '407', 'title': 'Total Made'},
             {'abrv': 'FGA', 'stat_id': '408', 'title': 'Total Attempted'},
             {'abrv': 'FGLong', 'stat_id': '410', 'title': 'Long'},
             {'abrv': 'XPM', 'stat_id': '411', 'title': 'Extra Points Made'},
             {'abrv': 'XPA', 'stat_id': '412', 'title': 'Extra Points Attempted'},
             {'abrv': 'Pts', 'stat_id': '413', 'title': 'Points'},
             {'abrv': 'KR', 'stat_id': '502', 'title': 'Kickoff Returns'},
             {'abrv': 'KRYds', 'stat_id': '503', 'title': 'Kick Return Yards'},
             {'abrv': 'KRTDs', 'stat_id': '507', 'title': 'Kick Return Touchdowns'},
             {'abrv': 'PR', 'stat_id': '508', 'title': 'Punt Returns'},
             {'abrv': 'PRYds', 'stat_id': '509', 'title': 'Punt Return Yards'},
             {'abrv': 'PRTDs', 'stat_id': '513', 'title': 'Punt Return Touchdowns'},
             {'abrv': 'Pnt', 'stat_id': '602', 'title': 'Punts'},
             {'abrv': 'PntAvg', 'stat_id': '604', 'title': 'Punt Average'},
             {'abrv': 'PntIn20', 'stat_id': '605', 'title': 'Punts in 20'},
             {'abrv': 'PntTB', 'stat_id': '607', 'title': 'Touchbacks'},
             {'abrv': 'Tkl', 'stat_id': '704', 'title': 'Total Tackles'},
             {'abrv': 'DefSacks', 'stat_id': '705', 'title': 'Sacks'},
             {'abrv': 'DefInts', 'stat_id': '707', 'title': 'Interceptions'},
             {'abrv': 'IntYds', 'stat_id': '708', 'title': 'Yards'},
             {'abrv': 'IntTDs', 'stat_id': '709', 'title': 'Interception Touchdowns'},
             {'abrv': 'PaDef', 'stat_id': '710', 'title': 'Passes Defended'},
             {'abrv': 'FirstD', 'stat_id': '919', 'title': 'First Downs'},
             {'abrv': 'TmRuAtt', 'stat_id': '920', 'title': 'Rushes'},
             {'abrv': 'TmRuYds', 'stat_id': '921', 'title': 'Net Yards Rushing'},
             {'abrv': 'TmINTS', 'stat_id': '926', 'title': 'Interceptions Thrown'},
             {'abrv': 'TmPaSACKS', 'stat_id': '927', 'title': 'Times Sacked'},
             {'abrv': 'TmPaSACKYds', 'stat_id': '928', 'title': 'Yds Lost To Sacks'},
             {'abrv': 'TmPnt', 'stat_id': '929', 'title': 'Punts'},
             {'abrv': 'TmFum', 'stat_id': '932', 'title': 'Fumbles Lost'},
             {'abrv': 'PEN', 'stat_id': '933', 'title': 'Penalties'},
             {'abrv': 'PENYds', 'stat_id': '934', 'title': 'Penalty Yards'},
             {'abrv': 'POSSTIME', 'stat_id': '935', 'title': 'Time of Possession'},
             {'abrv': 'RUSHF', 'stat_id': '936', 'title': 'Rushes for First'},
             {'abrv': 'PASSF', 'stat_id': '937', 'title': 'Passes for First'},
             {'abrv': 'PENF', 'stat_id': '938', 'title': 'Penalties for First'},
             ###
             # {'abrv': '3DE', 'stat_id': '941', 'title': 'Third Down Efficiency'},
             {'abrv': '3DAtt', 'stat_id': '939', 'title': 'Third Down Attempt'},
             {'abrv': '3DComp', 'stat_id': '940', 'title': 'Third Down Complete'},
             # {'abrv': '4DE', 'stat_id': '944', 'title': 'Fourth Down Efficiency'},
             {'abrv': '4DAtt', 'stat_id': '942', 'title': 'Fourth Down Efficiency'},
             {'abrv': '4DComp', 'stat_id': '943', 'title': 'Fourth Down Efficiency'},
             ###
             {'abrv': 'TmYDS', 'stat_id': '945', 'title': 'Total Yards'},
             {'abrv': 'PLAYS', 'stat_id': '946', 'title': 'Total Plays'},
             {'abrv': 'TmPaYds', 'stat_id': '947', 'title': 'Net Yards Passing'},
             {'abrv': 'TO', 'stat_id': '950', 'title': 'Turnovers'},
             ###
             # {'abrv': 'PASSEFF', 'stat_id': '951', 'title': 'Comp-Att'},
             {'abrv': 'TmPaAtt', 'stat_id': '954', 'title': 'Team Pass Attempts'},
             {'abrv': 'TmPaComp', 'stat_id': '953', 'title': 'Team Pass Completions'},
             ###
             {'abrv': 'Points', 'stat_id': '963', 'title': 'Team Points'}]


positionTypes = [{'abrv': 'TE', 'pos_id': '7', 'title': 'Tight End'},
                 {'abrv': 'QB', 'pos_id': '8', 'title': 'Quarterback'},
                 {'abrv': 'RB', 'pos_id': '9', 'title': 'Running Back'},
                 {'abrv': 'LB', 'pos_id': '30', 'title': 'Linebacker'},
                 {'abrv': 'DE', 'pos_id': '31', 'title': 'Defensive End'},
                 {'abrv': 'DT', 'pos_id': '32', 'title': 'Defensive Tackle'},
                 {'abrv': 'K', 'pos_id': '22', 'title': 'Kicker'},
                 {'abrv': 'P', 'pos_id': '23', 'title': 'Punter'},
                 {'abrv': 'WR', 'pos_id': '1', 'title': 'Wide Receiver'},
                 {'abrv': 'S', 'pos_id': '36', 'title': 'Safety'},
                 {'abrv': 'LS', 'pos_id': '39', 'title': 'Long Snapper'},
                 {'abrv': 'CB', 'pos_id': '29', 'title': 'Cornerback'},
                 {'abrv': 'FB', 'pos_id': '10', 'title': 'Fullback'},
                 {'abrv': 'DL', 'pos_id': '45', 'title': 'Defensive Lineman'},
                 {'abrv': 'DB', 'pos_id': '35', 'title': 'Defensive Back'},
                 {'abrv': 'NT', 'pos_id': '12', 'title': 'Nose Tackle'},
                 {'abrv': 'OL', 'pos_id': '44', 'title': 'Offensive Lineman'},
                 {'abrv': 'G', 'pos_id': '91', 'title': 'Guard'},
                 {'abrv': 'T', 'pos_id': '95', 'title': 'Tackle'},
                 {'abrv': 'N/A', 'pos_id': '40', 'title': 'UNDEFINED POS'},
                 {'abrv': 'C', 'pos_id': '4', 'title': 'Center'}]


teams = [{'abrv': 'MTSU',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'Middle Tennessee',
  'last_name': 'Blue Raiders',
  'primary_color': '000000',
  'secondary_color': '0066cc',
  'team_id': '152'},
 {'abrv': 'UAB',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'UAB',
  'last_name': 'Blazers',
  'primary_color': '006341',
  'secondary_color': 'cc8a00',
  'team_id': '207'},
 {'abrv': 'CAL',
  'conference': 'PAC12',
  'division': 'North Division',
  'first_name': 'California',
  'last_name': 'Golden Bears',
  'primary_color': '003262',
  'secondary_color': '3b7ea1',
  'team_id': '59'},
 {'abrv': 'ORE',
  'conference': 'PAC12',
  'division': 'North Division',
  'first_name': 'Oregon',
  'last_name': 'Ducks',
  'primary_color': '003300',
  'secondary_color': 'f5ed1c',
  'team_id': '60'},
 {'abrv': 'ORST',
  'conference': 'PAC12',
  'division': 'North Division',
  'first_name': 'Oregon State',
  'last_name': 'Beavers',
  'primary_color': '000000',
  'secondary_color': 'ff8c1f',
  'team_id': '61'},
 {'abrv': 'GT',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'Georgia Tech',
  'last_name': 'Yellow Jackets',
  'primary_color': 'b3a369',
  'secondary_color': '003057',
  'team_id': '4'},
 {'abrv': 'UCF',
  'conference': 'AAC',
  'division': 'East Division',
  'first_name': 'UCF',
  'last_name': 'Knights',
  'primary_color': '000000',
  'secondary_color': 'ba9a4c',
  'team_id': '210'},
 {'abrv': 'BSU',
  'conference': 'MWC',
  'division': 'Mountain Division',
  'first_name': 'Boise State',
  'last_name': 'Broncos',
  'primary_color': '003399',
  'secondary_color': 'ff6633',
  'team_id': '112'},
 {'abrv': 'RICE',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'Rice',
  'last_name': 'Owls',
  'primary_color': '00205b',
  'secondary_color': 'c1c6c8',
  'team_id': '81'},
 {'abrv': 'ISU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Iowa State',
  'last_name': 'Cyclones',
  'primary_color': 'c8102e',
  'secondary_color': 'f1be48',
  'team_id': '19'},
 {'abrv': 'OSU',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Ohio State',
  'last_name': 'Buckeyes',
  'primary_color': 'bb0000',
  'secondary_color': '666666',
  'team_id': '33'},
 {'abrv': 'ARK',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'Arkansas',
  'last_name': 'Razorbacks',
  'primary_color': '9e1b32',
  'secondary_color': '828a8f',
  'team_id': '74'},
 {'abrv': 'IND',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Indiana',
  'last_name': 'Hoosiers',
  'primary_color': '990000',
  'secondary_color': 'eeedeb',
  'team_id': '27'},
 {'abrv': 'SMU',
  'conference': 'AAC',
  'division': 'West Division',
  'first_name': 'SMU',
  'last_name': 'Mustangs',
  'primary_color': '000033',
  'secondary_color': 'cc0000',
  'team_id': '82'},
 {'abrv': 'UK',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'Kentucky',
  'last_name': 'Wildcats',
  'primary_color': '0033a0',
  'secondary_color': 'ffffff',
  'team_id': '69'},
 {'abrv': 'WMU',
  'conference': 'MIDAM',
  'division': 'West Division',
  'first_name': 'Western Michigan',
  'last_name': 'Broncos',
  'primary_color': '6c4023',
  'secondary_color': 'b5a167',
  'team_id': '56'},
 {'abrv': 'BALL',
  'conference': 'MIDAM',
  'division': 'West Division',
  'first_name': 'Ball State',
  'last_name': 'Cardinals',
  'primary_color': 'ba0c2f',
  'secondary_color': '000000',
  'team_id': '48'},
 {'abrv': 'TEX',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Texas',
  'last_name': 'Longhorns',
  'primary_color': 'bf5700',
  'secondary_color': '333f48',
  'team_id': '83'},
 {'abrv': 'UTAH',
  'conference': 'PAC12',
  'division': 'South Division',
  'first_name': 'Utah',
  'last_name': 'Utes',
  'primary_color': 'cc0000',
  'secondary_color': 'cdcdcd',
  'team_id': '94'},
 {'abrv': 'MSU',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Michigan State',
  'last_name': 'Spartans',
  'primary_color': '18453b',
  'secondary_color': 'ffffff',
  'team_id': '30'},
 {'abrv': 'SC',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'South Carolina',
  'last_name': 'Gamecocks',
  'primary_color': '73000a',
  'secondary_color': '000000',
  'team_id': '70'},
 {'abrv': 'PSU',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Penn State',
  'last_name': 'Nittany Lions',
  'primary_color': '093162',
  'secondary_color': 'ffffff',
  'team_id': '34'},
 {'abrv': 'AUB',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'Auburn',
  'last_name': 'Tigers',
  'primary_color': '0c2340',
  'secondary_color': 'e87722',
  'team_id': '75'},
 {'abrv': 'USU',
  'conference': 'MWC',
  'division': 'Mountain Division',
  'first_name': 'Utah State',
  'last_name': 'Aggies',
  'primary_color': '003263',
  'secondary_color': 'ffffff',
  'team_id': '46'},
 {'abrv': 'DUKE',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'Duke',
  'last_name': 'Blue Devils',
  'primary_color': '003087',
  'secondary_color': 'ffffff',
  'team_id': '2'},
 {'abrv': 'UGA',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'Georgia',
  'last_name': 'Bulldogs',
  'primary_color': 'ba0c2f',
  'secondary_color': '000000',
  'team_id': '68'},
 {'abrv': 'TOL',
  'conference': 'MIDAM',
  'division': 'West Division',
  'first_name': 'Toledo',
  'last_name': 'Rockets',
  'primary_color': '15397f',
  'secondary_color': 'ffda00',
  'team_id': '55'},
 {'abrv': 'S FLA',
  'conference': 'AAC',
  'division': 'East Division',
  'first_name': 'South Florida',
  'last_name': 'Bulls',
  'primary_color': '006747',
  'secondary_color': 'cfc493',
  'team_id': '1019'},
 {'abrv': 'AFA',
  'conference': 'MWC',
  'division': 'Mountain Division',
  'first_name': 'Air Force',
  'last_name': 'Falcons',
  'primary_color': '003087',
  'secondary_color': '8a8d8f',
  'team_id': '87'},
 {'abrv': 'ULM',
  'conference': 'SBELT',
  'division': 'West Division',
  'first_name': 'Louisiana-Monroe',
  'last_name': 'Warhawks',
  'primary_color': '800029',
  'secondary_color': 'bd955a',
  'team_id': '103'},
 {'abrv': 'MEM',
  'conference': 'AAC',
  'division': 'West Division',
  'first_name': 'Memphis',
  'last_name': 'Tigers',
  'primary_color': '003087',
  'secondary_color': '898d8d',
  'team_id': '101'},
 {'abrv': 'VT',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'Virginia Tech',
  'last_name': 'Hokies',
  'primary_color': '630031',
  'secondary_color': 'cf4420',
  'team_id': '16'},
 {'abrv': 'MICH',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Michigan',
  'last_name': 'Wolverines',
  'primary_color': '00274c',
  'secondary_color': 'ffcb05',
  'team_id': '29'},
 {'abrv': 'GA ST',
  'conference': 'SBELT',
  'division': 'East Division',
  'first_name': 'Georgia State',
  'last_name': 'Panthers',
  'primary_color': '0039a6',
  'secondary_color': 'c60c30',
  'team_id': '2558'},
 {'abrv': 'FIU',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'FIU',
  'last_name': 'Panthers',
  'primary_color': '081e3f',
  'secondary_color': 'b6862c',
  'team_id': '2307'},
 {'abrv': 'HAW',
  'conference': 'MWC',
  'division': 'West Division',
  'first_name': 'Hawaii',
  'last_name': 'Rainbow Warriors',
  'primary_color': '024731',
  'secondary_color': 'c8c8c8',
  'team_id': '91'},
 {'abrv': 'LSU',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'LSU',
  'last_name': 'Tigers',
  'primary_color': '461d7c',
  'secondary_color': 'fdd023',
  'team_id': '76'},
 {'abrv': 'S ALA',
  'conference': 'SBELT',
  'division': 'West Division',
  'first_name': 'South Alabama',
  'last_name': 'Jaguars',
  'primary_color': '00205b',
  'secondary_color': 'bf0d3e',
  'team_id': '2549'},
 {'abrv': 'USM',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'Southern Miss',
  'last_name': 'Golden Eagles',
  'primary_color': '000000',
  'secondary_color': 'ffab00',
  'team_id': '105'},
 {'abrv': 'MINN',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Minnesota',
  'last_name': 'Golden Gophers',
  'primary_color': '7a0019',
  'secondary_color': 'ffcc33',
  'team_id': '31'},
 {'abrv': 'IOWA',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Iowa',
  'last_name': 'Hawkeyes',
  'primary_color': '000000',
  'secondary_color': '000000',
  'team_id': '28'},
 {'abrv': 'ND',
  'conference': 'IA',
  'division': None,
  'first_name': 'Notre Dame',
  'last_name': 'Fighting Irish',
  'primary_color': '0c2340',
  'secondary_color': 'c99700',
  'team_id': '104'},
 {'abrv': 'WVU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'West Virginia',
  'last_name': 'Mountaineers',
  'primary_color': '002855',
  'secondary_color': 'eaaa00',
  'team_id': '17'},
 {'abrv': 'ASU',
  'conference': 'PAC12',
  'division': 'South Division',
  'first_name': 'Arizona State',
  'last_name': 'Sun Devils',
  'primary_color': '8c1d40',
  'secondary_color': 'ffc627',
  'team_id': '58'},
 {'abrv': 'PUR',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Purdue',
  'last_name': 'Boilermakers',
  'primary_color': 'ceb888',
  'secondary_color': '000000',
  'team_id': '35'},
 {'abrv': 'WAKE',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'Wake Forest',
  'last_name': 'Demon Deacons',
  'primary_color': 'a67f31',
  'secondary_color': '000000',
  'team_id': '9'},
 {'abrv': 'WKU',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'Western Kentucky',
  'last_name': 'Hilltoppers',
  'primary_color': 'c60c30',
  'secondary_color': '1e1e1e',
  'team_id': '224'},
 {'abrv': 'M-OH',
  'conference': 'MIDAM',
  'division': 'East Division',
  'first_name': 'Miami (OH)',
  'last_name': 'RedHawks',
  'primary_color': 'b61e2e',
  'secondary_color': '000000',
  'team_id': '53'},
 {'abrv': 'TLSA',
  'conference': 'AAC',
  'division': 'West Division',
  'first_name': 'Tulsa',
  'last_name': 'Golden Hurricane',
  'primary_color': '002d72',
  'secondary_color': 'c8102e',
  'team_id': '107'},
 {'abrv': 'PITT',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'Pittsburgh',
  'last_name': 'Panthers',
  'primary_color': '003594',
  'secondary_color': 'ffb81c',
  'team_id': '12'},
 {'abrv': 'WSU',
  'conference': 'PAC12',
  'division': 'North Division',
  'first_name': 'Washington State',
  'last_name': 'Cougars',
  'primary_color': '680000',
  'secondary_color': 'cdcdcd',
  'team_id': '66'},
 {'abrv': 'LIB',
  'conference': 'IA',
  'division': None,
  'first_name': 'Liberty',
  'last_name': 'Flames',
  'primary_color': '00315c',
  'secondary_color': 'cc0000',
  'team_id': '215'},
 {'abrv': 'BC',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'Boston College',
  'last_name': 'Eagles',
  'primary_color': '98002e',
  'secondary_color': 'bc9b6a',
  'team_id': '10'},
 {'abrv': 'ULL',
  'conference': 'SBELT',
  'division': 'West Division',
  'first_name': 'Louisiana',
  'last_name': "Ragin' Cajuns",
  'primary_color': 'ce181e',
  'secondary_color': '0a0203',
  'team_id': '45'},
 {'abrv': 'TTU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Texas Tech',
  'last_name': 'Red Raiders',
  'primary_color': 'cc0000',
  'secondary_color': '000000',
  'team_id': '86'},
 {'abrv': 'UMD',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Maryland',
  'last_name': 'Terrapins',
  'primary_color': 'e03a3e',
  'secondary_color': 'ffd520',
  'team_id': '5'},
 {'abrv': 'UNC',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'North Carolina',
  'last_name': 'Tar Heels',
  'primary_color': '7bafd4',
  'secondary_color': 'ffffff',
  'team_id': '6'},
 {'abrv': 'KENT',
  'conference': 'MIDAM',
  'division': 'East Division',
  'first_name': 'Kent State',
  'last_name': 'Golden Flashes',
  'primary_color': '002664',
  'secondary_color': 'eaab00',
  'team_id': '52'},
 {'abrv': 'CIN',
  'conference': 'AAC',
  'division': 'East Division',
  'first_name': 'Cincinnati',
  'last_name': 'Bearcats',
  'primary_color': 'e00122',
  'secondary_color': '000000',
  'team_id': '98'},
 {'abrv': 'ARIZ',
  'conference': 'PAC12',
  'division': 'South Division',
  'first_name': 'Arizona',
  'last_name': 'Wildcats',
  'primary_color': 'cc0033',
  'secondary_color': '003366',
  'team_id': '57'},
 {'abrv': 'ARMY',
  'conference': 'IA',
  'division': None,
  'first_name': 'Army West Point',
  'last_name': 'Black Knights',
  'primary_color': '000000',
  'secondary_color': 'bb9c6c',
  'team_id': '97'},
 {'abrv': 'COLO',
  'conference': 'PAC12',
  'division': 'South Division',
  'first_name': 'Colorado',
  'last_name': 'Buffaloes',
  'primary_color': 'cfb87c',
  'secondary_color': '000000',
  'team_id': '18'},
 {'abrv': 'GASO',
  'conference': 'SBELT',
  'division': 'East Division',
  'first_name': 'Georgia Southern',
  'last_name': 'Eagles',
  'primary_color': '011e41',
  'secondary_color': 'a3aaae',
  'team_id': '175'},
 {'abrv': 'KU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Kansas',
  'last_name': 'Jayhawks',
  'primary_color': '0051ba',
  'secondary_color': 'e8000d',
  'team_id': '20'},
 {'abrv': 'TROY',
  'conference': 'SBELT',
  'division': 'East Division',
  'first_name': 'Troy',
  'last_name': 'Trojans',
  'primary_color': '910029',
  'secondary_color': '86878b',
  'team_id': '222'},
 {'abrv': 'FAU',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'Florida Atlantic',
  'last_name': 'Owls',
  'primary_color': '003366',
  'secondary_color': 'cc0000',
  'team_id': '2294'},
 {'abrv': 'ARST',
  'conference': 'SBELT',
  'division': 'West Division',
  'first_name': 'Arkansas State',
  'last_name': 'Red Wolves',
  'primary_color': 'cc092f',
  'secondary_color': '000000',
  'team_id': '37'},
 {'abrv': 'HOU',
  'conference': 'AAC',
  'division': 'West Division',
  'first_name': 'Houston',
  'last_name': 'Cougars',
  'primary_color': 'c8102e',
  'secondary_color': '76232f',
  'team_id': '80'},
 {'abrv': 'NCST',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'North Carolina State',
  'last_name': 'Wolfpack',
  'primary_color': 'cc0000',
  'secondary_color': '000000',
  'team_id': '7'},
 {'abrv': 'OHIO',
  'conference': 'MIDAM',
  'division': 'East Division',
  'first_name': 'Ohio',
  'last_name': 'Bobcats',
  'primary_color': '00694e',
  'secondary_color': 'cda077',
  'team_id': '54'},
 {'abrv': 'UMASS',
  'conference': 'IA',
  'division': None,
  'first_name': 'Massachusetts',
  'last_name': 'Minutemen',
  'primary_color': '971b2f',
  'secondary_color': '572932',
  'team_id': '204'},
 {'abrv': 'CMU',
  'conference': 'MIDAM',
  'division': 'West Division',
  'first_name': 'Central Michigan',
  'last_name': 'Chippewas',
  'primary_color': '6a0032',
  'secondary_color': 'ffc82e',
  'team_id': '50'},
 {'abrv': 'BYU',
  'conference': 'IA',
  'division': None,
  'first_name': 'BYU',
  'last_name': 'Cougars',
  'primary_color': '002255',
  'secondary_color': 'c5af7d',
  'team_id': '88'},
 {'abrv': 'NMSU',
  'conference': 'IA',
  'division': None,
  'first_name': 'New Mexico State',
  'last_name': 'Aggies',
  'primary_color': '861f41',
  'secondary_color': '97999b',
  'team_id': '41'},
 {'abrv': 'TXST',
  'conference': 'SBELT',
  'division': 'West Division',
  'first_name': 'Texas State',
  'last_name': 'Bobcats',
  'primary_color': '501214',
  'secondary_color': '8d734a',
  'team_id': '185'},
 {'abrv': 'STAN',
  'conference': 'PAC12',
  'division': 'North Division',
  'first_name': 'Stanford',
  'last_name': 'Cardinal',
  'primary_color': '990000',
  'secondary_color': 'ffffff',
  'team_id': '63'},
 {'abrv': 'AKR',
  'conference': 'MIDAM',
  'division': 'East Division',
  'first_name': 'Akron',
  'last_name': 'Zips',
  'primary_color': '041e42',
  'secondary_color': 'a89968',
  'team_id': '47'},
 {'abrv': 'TULN',
  'conference': 'AAC',
  'division': 'West Division',
  'first_name': 'Tulane',
  'last_name': 'Green Wave',
  'primary_color': '006747',
  'secondary_color': '43b02a',
  'team_id': '106'},
 {'abrv': 'UCLA',
  'conference': 'PAC12',
  'division': 'South Division',
  'first_name': 'UCLA',
  'last_name': 'Bruins',
  'primary_color': '77aafd',
  'secondary_color': 'ffcc00',
  'team_id': '64'},
 {'abrv': 'BGSU',
  'conference': 'MIDAM',
  'division': 'East Division',
  'first_name': 'Bowling Green',
  'last_name': 'Falcons',
  'primary_color': 'fe5000',
  'secondary_color': '4f2c1d',
  'team_id': '49'},
 {'abrv': 'OU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Oklahoma',
  'last_name': 'Sooners',
  'primary_color': '841617',
  'secondary_color': 'fdf9d8',
  'team_id': '24'},
 {'abrv': 'SDSU',
  'conference': 'MWC',
  'division': 'West Division',
  'first_name': 'San Diego State',
  'last_name': 'Aztecs',
  'primary_color': 'a6192e',
  'secondary_color': '000000',
  'team_id': '93'},
 {'abrv': 'UW',
  'conference': 'PAC12',
  'division': 'North Division',
  'first_name': 'Washington',
  'last_name': 'Huskies',
  'primary_color': '330066',
  'secondary_color': 'cebf8f',
  'team_id': '65'},
 {'abrv': 'NEB',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Nebraska',
  'last_name': 'Cornhuskers',
  'primary_color': 'e41c38',
  'secondary_color': '000000',
  'team_id': '23'},
 {'abrv': 'SYR',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'Syracuse',
  'last_name': 'Orange',
  'primary_color': 'd44500',
  'secondary_color': '3e3d3c',
  'team_id': '14'},
 {'abrv': 'USC',
  'conference': 'PAC12',
  'division': 'South Division',
  'first_name': 'USC',
  'last_name': 'Trojans',
  'primary_color': '750000',
  'secondary_color': 'ffcc00',
  'team_id': '62'},
 {'abrv': 'UNLV',
  'conference': 'MWC',
  'division': 'West Division',
  'first_name': 'UNLV',
  'last_name': 'Rebels',
  'primary_color': 'b10202',
  'secondary_color': '666666',
  'team_id': '40'},
 {'abrv': 'UTSA',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'UTSA',
  'last_name': 'Roadrunners',
  'primary_color': 'f15a22',
  'secondary_color': '0c2340',
  'team_id': '2560'},
 {'abrv': 'TCU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'TCU',
  'last_name': 'Horned Frogs',
  'primary_color': '4d1979',
  'secondary_color': 'a3a9ac',
  'team_id': '85'},
 {'abrv': 'ODU',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'Old Dominion',
  'last_name': 'Monarchs',
  'primary_color': '003057',
  'secondary_color': '7c878e',
  'team_id': '2371'},
 {'abrv': 'SJSU',
  'conference': 'MWC',
  'division': 'West Division',
  'first_name': 'San Jose State',
  'last_name': 'Spartans',
  'primary_color': '0055a2',
  'secondary_color': 'e5a823',
  'team_id': '44'},
 {'abrv': 'ECU',
  'conference': 'AAC',
  'division': 'East Division',
  'first_name': 'East Carolina',
  'last_name': 'Pirates',
  'primary_color': '592a8a',
  'secondary_color': 'fdc82f',
  'team_id': '99'},
 {'abrv': 'RUTG',
  'conference': 'BTEN',
  'division': 'East Division',
  'first_name': 'Rutgers',
  'last_name': 'Scarlet Knights',
  'primary_color': 'cc0033',
  'secondary_color': '5f6a72',
  'team_id': '13'},
 {'abrv': 'MISS',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'Ole Miss',
  'last_name': 'Rebels',
  'primary_color': 'ce1126',
  'secondary_color': '14213d',
  'team_id': '77'},
 {'abrv': 'LOU',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'Louisville',
  'last_name': 'Cardinals',
  'primary_color': 'ad0000',
  'secondary_color': 'fdb913',
  'team_id': '100'},
 {'abrv': 'WIS',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Wisconsin',
  'last_name': 'Badgers',
  'primary_color': 'c5050c',
  'secondary_color': 'ffffff',
  'team_id': '36'},
 {'abrv': 'ILL',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Illinois',
  'last_name': 'Fighting Illini',
  'primary_color': '13294b',
  'secondary_color': 'e84a27',
  'team_id': '26'},
 {'abrv': 'NEV',
  'conference': 'MWC',
  'division': 'West Division',
  'first_name': 'Nevada',
  'last_name': 'Wolf Pack',
  'primary_color': '003366',
  'secondary_color': '807f84',
  'team_id': '39'},
 {'abrv': 'FRES',
  'conference': 'MWC',
  'division': 'West Division',
  'first_name': 'Fresno State',
  'last_name': 'Bulldogs',
  'primary_color': 'db0032',
  'secondary_color': '002e6d',
  'team_id': '90'},
 {'abrv': 'EMU',
  'conference': 'MIDAM',
  'division': 'West Division',
  'first_name': 'Eastern Michigan',
  'last_name': 'Eagles',
  'primary_color': '006633',
  'secondary_color': '000000',
  'team_id': '51'},
 {'abrv': 'MRSH',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'Marshall',
  'last_name': 'Thundering Herd',
  'primary_color': '00b140',
  'secondary_color': 'a2aaad',
  'team_id': '176'},
 {'abrv': 'WYO',
  'conference': 'MWC',
  'division': 'Mountain Division',
  'first_name': 'Wyoming',
  'last_name': 'Cowboys',
  'primary_color': 'ffc425',
  'secondary_color': '492f24',
  'team_id': '96'},
 {'abrv': 'CLEM',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'Clemson',
  'last_name': 'Tigers',
  'primary_color': 'f56600',
  'secondary_color': '522d80',
  'team_id': '1'},
 {'abrv': 'CSU',
  'conference': 'MWC',
  'division': 'Mountain Division',
  'first_name': 'Colorado State',
  'last_name': 'Rams',
  'primary_color': '1e4d2b',
  'secondary_color': 'c8c372',
  'team_id': '89'},
 {'abrv': 'OKST',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Oklahoma State',
  'last_name': 'Cowboys',
  'primary_color': 'ff7300',
  'secondary_color': 'bebebe',
  'team_id': '25'},
 {'abrv': 'UNT',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'North Texas',
  'last_name': 'Mean Green',
  'primary_color': '00853e',
  'secondary_color': '000000',
  'team_id': '182'},
 {'abrv': 'KSU',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Kansas State',
  'last_name': 'Wildcats',
  'primary_color': '512888',
  'secondary_color': 'd1d1d1',
  'team_id': '21'},
 {'abrv': 'APP',
  'conference': 'SBELT',
  'division': 'East Division',
  'first_name': 'Appalachian State',
  'last_name': 'Mountaineers',
  'primary_color': '222222',
  'secondary_color': 'ffcc00',
  'team_id': '171'},
 {'abrv': 'UTEP',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'UTEP',
  'last_name': 'Miners',
  'primary_color': '150041',
  'secondary_color': '041e42',
  'team_id': '95'},
 {'abrv': 'VAN',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'Vanderbilt',
  'last_name': 'Commodores',
  'primary_color': '000000',
  'secondary_color': '866d4b',
  'team_id': '72'},
 {'abrv': 'NAVY',
  'conference': 'AAC',
  'division': 'West Division',
  'first_name': 'Navy',
  'last_name': 'Midshipmen',
  'primary_color': '00205b',
  'secondary_color': 'c5b783',
  'team_id': '102'},
 {'abrv': 'NIU',
  'conference': 'MIDAM',
  'division': 'West Division',
  'first_name': 'Northern Illinois',
  'last_name': 'Huskies',
  'primary_color': 'ba0c2f',
  'secondary_color': '8a8d8f',
  'team_id': '42'},
 {'abrv': 'FLA',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'Florida',
  'last_name': 'Gators',
  'primary_color': '0021a5',
  'secondary_color': 'fa4616',
  'team_id': '67'},
 {'abrv': 'UVA',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'Virginia',
  'last_name': 'Cavaliers',
  'primary_color': '232d4b',
  'secondary_color': 'f84c1e',
  'team_id': '8'},
 {'abrv': 'CHAR',
  'conference': 'CUSA',
  'division': 'East Division',
  'first_name': 'Charlotte',
  'last_name': '49ers',
  'primary_color': '046a38',
  'secondary_color': 'b9975b',
  'team_id': '2595'},
 {'abrv': 'TEM',
  'conference': 'AAC',
  'division': 'East Division',
  'first_name': 'Temple',
  'last_name': 'Owls',
  'primary_color': '9d2235',
  'secondary_color': 'ffcd00',
  'team_id': '15'},
 {'abrv': 'ALA',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'Alabama',
  'last_name': 'Crimson Tide',
  'primary_color': '9e1b32',
  'secondary_color': '828a8f',
  'team_id': '73'},
 {'abrv': 'FSU',
  'conference': 'ACC',
  'division': 'Atlantic Division',
  'first_name': 'Florida State',
  'last_name': 'Seminoles',
  'primary_color': '782f40',
  'secondary_color': 'ceb888',
  'team_id': '3'},
 {'abrv': 'CCU',
  'conference': 'SBELT',
  'division': 'East Division',
  'first_name': 'Coastal Carolina',
  'last_name': 'Chanticleers',
  'primary_color': '006f71',
  'secondary_color': '000000',
  'team_id': '2316'},
 {'abrv': 'MIA',
  'conference': 'ACC',
  'division': 'Coastal Division',
  'first_name': 'Miami (FL)',
  'last_name': 'Hurricanes',
  'primary_color': 'f47321',
  'secondary_color': '005030',
  'team_id': '11'},
 {'abrv': 'BUFF',
  'conference': 'MIDAM',
  'division': 'East Division',
  'first_name': 'Buffalo',
  'last_name': 'Bulls',
  'primary_color': '005bbb',
  'secondary_color': 'ffffff',
  'team_id': '208'},
 {'abrv': 'UNM',
  'conference': 'MWC',
  'division': 'Mountain Division',
  'first_name': 'New Mexico',
  'last_name': 'Lobos',
  'primary_color': 'ba0c2f',
  'secondary_color': 'a7a8aa',
  'team_id': '92'},
 {'abrv': 'TENN',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'Tennessee',
  'last_name': 'Volunteers',
  'primary_color': 'ff8200',
  'secondary_color': '58595b',
  'team_id': '71'},
 {'abrv': 'MSST',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'Mississippi State',
  'last_name': 'Bulldogs',
  'primary_color': '660000',
  'secondary_color': 'ffffff',
  'team_id': '78'},
 {'abrv': 'CONN',
  'conference': 'IA',
  'division': None,
  'first_name': 'Connecticut',
  'last_name': 'Huskies',
  'primary_color': '00036e',
  'secondary_color': 'dedede',
  'team_id': '202'},
 {'abrv': 'LT',
  'conference': 'CUSA',
  'division': 'West Division',
  'first_name': 'Louisiana Tech',
  'last_name': 'Bulldogs',
  'primary_color': '002f8b',
  'secondary_color': 'e31b23',
  'team_id': '38'},
 {'abrv': 'TAMU',
  'conference': 'SEC',
  'division': 'West Division',
  'first_name': 'Texas A&M',
  'last_name': 'Aggies',
  'primary_color': '500000',
  'secondary_color': 'ffffff',
  'team_id': '84'},
 {'abrv': 'NW',
  'conference': 'BTEN',
  'division': 'West Division',
  'first_name': 'Northwestern',
  'last_name': 'Wildcats',
  'primary_color': '4e2a84',
  'secondary_color': 'ffffff',
  'team_id': '32'},
 {'abrv': 'MIZZ',
  'conference': 'SEC',
  'division': 'East Division',
  'first_name': 'Missouri',
  'last_name': 'Tigers',
  'primary_color': '000000',
  'secondary_color': 'f1b82d',
  'team_id': '22'},
 {'abrv': 'BAY',
  'conference': 'BIG12',
  'division': None,
  'first_name': 'Baylor',
  'last_name': 'Bears',
  'primary_color': '003015',
  'secondary_color': 'fecb00',
  'team_id': '79'},
 {'abrv': 'WAG',
  'conference': 'NEC',
  'division': None,
  'first_name': 'Wagner',
  'last_name': 'Seahawks',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '223'},
 {'abrv': 'MOST',
  'conference': 'MVC',
  'division': None,
  'first_name': 'Missouri State',
  'last_name': 'Bears',
  'primary_color': '5e0009',
  'secondary_color': 'ffffff',
  'team_id': '125'},
 {'abrv': 'MERC',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Mercer',
  'last_name': 'Bears',
  'primary_color': 'f76800',
  'secondary_color': '000000',
  'team_id': '2597'},
 {'abrv': 'MAINE',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Maine',
  'last_name': 'Black Bears',
  'primary_color': '003263',
  'secondary_color': 'b0d7ff',
  'team_id': '203'},
 {'abrv': 'UNI',
  'conference': 'MVC',
  'division': None,
  'first_name': 'UNI',
  'last_name': 'Panthers',
  'primary_color': '4b116f',
  'secondary_color': 'ffcc00',
  'team_id': '123'},
 {'abrv': 'TNST',
  'conference': 'OVC',
  'division': None,
  'first_name': 'Tennessee State',
  'last_name': 'Tigers',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '157'},
 {'abrv': 'ALST',
  'conference': 'SWAC',
  'division': 'East Division',
  'first_name': 'Alabama State',
  'last_name': 'Hornets',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '187'},
 {'abrv': 'NWST',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Northwestern State',
  'last_name': 'Demons',
  'primary_color': '552794',
  'secondary_color': 'fe7c00',
  'team_id': '183'},
 {'abrv': 'MONT',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Montana',
  'last_name': 'Grizzlies',
  'primary_color': '660033',
  'secondary_color': '999999',
  'team_id': '116'},
 {'abrv': 'ILST',
  'conference': 'MVC',
  'division': None,
  'first_name': 'Illinois State',
  'last_name': 'Redbirds',
  'primary_color': 'ce1126',
  'secondary_color': 'f9dd16',
  'team_id': '121'},
 {'abrv': 'COOK',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'Bethune-Cookman',
  'last_name': 'Wildcats',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '143'},
 {'abrv': 'HOW',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'Howard',
  'last_name': 'Bison',
  'primary_color': '012d6c',
  'secondary_color': 'd82c44',
  'team_id': '146'},
 {'abrv': 'CHSO',
  'conference': 'BSOU',
  'division': None,
  'first_name': 'Charleston Southern',
  'last_name': 'Buccaneers',
  'primary_color': '072f67',
  'secondary_color': 'c7ae5e',
  'team_id': '211'},
 {'abrv': 'CHAT',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Chattanooga',
  'last_name': 'Mocs',
  'primary_color': '00386b',
  'secondary_color': 'e0aa0f',
  'team_id': '177'},
 {'abrv': 'SAC',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Sacramento State',
  'last_name': 'Hornets',
  'primary_color': '01573C',
  'secondary_color': 'c4b581',
  'team_id': '110'},
 {'abrv': 'DEL',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Delaware',
  'last_name': "Fightin' Blue Hens",
  'primary_color': '0d1ba0',
  'secondary_color': 'ffd800',
  'team_id': '195'},
 {'abrv': 'ACU',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Abilene Christian',
  'last_name': 'Wildcats',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '276'},
 {'abrv': 'WOF',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Wofford',
  'last_name': 'Terriers',
  'primary_color': '886e4c',
  'secondary_color': '000000',
  'team_id': '267'},
 {'abrv': 'CCSU',
  'conference': 'NEC',
  'division': None,
  'first_name': 'Central Connecticut State',
  'last_name': 'Blue Devils',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '209'},
 {'abrv': 'NCAT',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'North Carolina A&T',
  'last_name': 'Aggies',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '148'},
 {'abrv': 'TXSO',
  'conference': 'SWAC',
  'division': 'West Division',
  'first_name': 'Texas Southern',
  'last_name': 'Tigers',
  'primary_color': '882a44',
  'secondary_color': 'ffffff',
  'team_id': '194'},
 {'abrv': 'VMI',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'VMI',
  'last_name': 'Keydets',
  'primary_color': 'a71f23',
  'secondary_color': 'ffd520',
  'team_id': '178'},
 {'abrv': 'STONY',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Stony Brook',
  'last_name': 'Seawolves',
  'primary_color': '990000',
  'secondary_color': '16243e',
  'team_id': '629'},
 {'abrv': 'SE LA',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Southeastern Louisiana',
  'last_name': 'Lions',
  'primary_color': '006545',
  'secondary_color': 'f0b809',
  'team_id': '2234'},
 {'abrv': 'IDHO',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Idaho',
  'last_name': 'Vandals',
  'primary_color': 'b3a369',
  'secondary_color': 'eaab00',
  'team_id': '114'},
 {'abrv': 'LAMR',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Lamar',
  'last_name': 'Cardinals',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2559'},
 {'abrv': 'WEB',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Weber State',
  'last_name': 'Wildcats',
  'primary_color': '4b2682',
  'secondary_color': 'a1a1a4',
  'team_id': '119'},
 {'abrv': 'EKY',
  'conference': 'OVC',
  'division': None,
  'first_name': 'Eastern Kentucky',
  'last_name': 'Colonels',
  'primary_color': '71283c',
  'secondary_color': 'ffffff',
  'team_id': '151'},
 {'abrv': 'ALBY',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Albany',
  'last_name': 'Great Danes',
  'primary_color': '461660',
  'secondary_color': 'eeb211',
  'team_id': '546'},
 {'abrv': 'KENN',
  'conference': 'BSOU',
  'division': None,
  'first_name': 'Kennesaw State',
  'last_name': 'Owls',
  'primary_color': 'fdbb30',
  'secondary_color': '0b1315',
  'team_id': '2610'},
 {'abrv': 'EWU',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Eastern Washington',
  'last_name': 'Eagles',
  'primary_color': 'a10022',
  'secondary_color': 'ffffff',
  'team_id': '113'},
 {'abrv': 'COLG',
  'conference': 'PATR',
  'division': None,
  'first_name': 'Colgate',
  'last_name': 'Raiders',
  'primary_color': '821019',
  'secondary_color': 'e10028',
  'team_id': '160'},
 {'abrv': 'URI',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Rhode Island',
  'last_name': 'Rams',
  'primary_color': '68abe8',
  'secondary_color': '002147',
  'team_id': '206'},
 {'abrv': 'TNTC',
  'conference': 'OVC',
  'division': None,
  'first_name': 'Tennessee Tech',
  'last_name': 'Golden Eagles',
  'primary_color': '5a008b',
  'secondary_color': 'fec401',
  'team_id': '158'},
 {'abrv': 'ELON',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Elon',
  'last_name': 'Phoenix',
  'primary_color': '670001',
  'secondary_color': 'a39568',
  'team_id': '350'},
 {'abrv': 'MTST',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Montana State',
  'last_name': 'Bobcats',
  'primary_color': '00205b',
  'secondary_color': 'b9975b',
  'team_id': '117'},
 {'abrv': 'PV',
  'conference': 'SWAC',
  'division': 'West Division',
  'first_name': 'Prairie View A&M',
  'last_name': 'Panthers',
  'primary_color': '49325E',
  'secondary_color': 'BBAD88',
  'team_id': '192'},
 {'abrv': 'JKST',
  'conference': 'SWAC',
  'division': 'East Division',
  'first_name': 'Jackson State',
  'last_name': 'Tigers',
  'primary_color': '00233f',
  'secondary_color': 'ffffff',
  'team_id': '190'},
 {'abrv': 'CAMP',
  'conference': 'BSOU',
  'division': None,
  'first_name': 'Campbell',
  'last_name': 'Fighting Camels',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2357'},
 {'abrv': 'UTM',
  'conference': 'OVC',
  'division': None,
  'first_name': 'UT Martin',
  'last_name': 'Skyhawks',
  'primary_color': '000099',
  'secondary_color': 'FF6600',
  'team_id': '156'},
 {'abrv': 'HBU',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Houston Baptist',
  'last_name': 'Huskies',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2601'},
 {'abrv': 'FOR',
  'conference': 'PATR',
  'division': None,
  'first_name': 'Fordham',
  'last_name': 'Rams',
  'primary_color': '860038',
  'secondary_color': 'ffffff',
  'team_id': '161'},
 {'abrv': 'SDAK',
  'conference': 'MVC',
  'division': None,
  'first_name': 'South Dakota',
  'last_name': 'Coyotes',
  'primary_color': 'ad0000',
  'secondary_color': 'b4b4b4',
  'team_id': '311'},
 {'abrv': 'BUCK',
  'conference': 'PATR',
  'division': None,
  'first_name': 'Bucknell',
  'last_name': 'Bison',
  'primary_color': 'e87722',
  'secondary_color': '003865',
  'team_id': '159'},
 {'abrv': 'IDST',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Idaho State',
  'last_name': 'Bengals',
  'primary_color': 'ff671f',
  'secondary_color': '000000',
  'team_id': '115'},
 {'abrv': 'JMU',
  'conference': 'CAA',
  'division': None,
  'first_name': 'James Madison',
  'last_name': 'Dukes',
  'primary_color': '441975',
  'secondary_color': 'f0daa1',
  'team_id': '196'},
 {'abrv': 'SOU',
  'conference': 'SWAC',
  'division': 'West Division',
  'first_name': 'Southern University',
  'last_name': 'Jaguars',
  'primary_color': '003798',
  'secondary_color': 'FFC726',
  'team_id': '193'},
 {'abrv': 'WIU',
  'conference': 'MVC',
  'division': None,
  'first_name': 'Western Illinois',
  'last_name': 'Leathernecks',
  'primary_color': '663399',
  'secondary_color': 'C3BD98',
  'team_id': '126'},
 {'abrv': 'UNCO',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Northern Colorado',
  'last_name': 'Bears',
  'primary_color': '001f3d',
  'secondary_color': 'f6b000',
  'team_id': '310'},
 {'abrv': 'ARPB',
  'conference': 'SWAC',
  'division': 'West Division',
  'first_name': 'Arkansas-Pine Bluff',
  'last_name': 'Golden Lions',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '589'},
 {'abrv': 'MONM',
  'conference': 'BSOU',
  'division': None,
  'first_name': 'Monmouth',
  'last_name': 'Hawks',
  'primary_color': '041e42',
  'secondary_color': '53565a',
  'team_id': '216'},
 {'abrv': 'SUU',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Southern Utah',
  'last_name': 'Thunderbirds',
  'primary_color': 'c41425',
  'secondary_color': '000000',
  'team_id': '111'},
 {'abrv': 'SAM',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Samford',
  'last_name': 'Bulldogs',
  'primary_color': '002649',
  'secondary_color': 'c4161d',
  'team_id': '218'},
 {'abrv': 'SIU',
  'conference': 'MVC',
  'division': None,
  'first_name': 'Southern Illinois',
  'last_name': 'Salukis',
  'primary_color': '720000',
  'secondary_color': 'ffffff',
  'team_id': '124'},
 {'abrv': 'WEBB',
  'conference': 'BSOU',
  'division': None,
  'first_name': 'Gardner-Webb',
  'last_name': "Runnin' Bulldogs",
  'primary_color': 'bf3038',
  'secondary_color': '000000',
  'team_id': '351'},
 {'abrv': 'FAMU',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'Florida A&M',
  'last_name': 'Rattlers',
  'primary_color': '00643a',
  'secondary_color': 'db3a19',
  'team_id': '145'},
 {'abrv': 'SEMO',
  'conference': 'OVC',
  'division': None,
  'first_name': 'Southeast Missouri State',
  'last_name': 'Redhawks',
  'primary_color': 'DA171D',
  'secondary_color': '000000',
  'team_id': '155'},
 {'abrv': 'HAMP',
  'conference': 'BSOU',
  'division': None,
  'first_name': 'Hampton',
  'last_name': 'Pirates',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '229'},
 {'abrv': 'TOWS',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Towson',
  'last_name': 'Tigers',
  'primary_color': 'ffb200',
  'secondary_color': '000000',
  'team_id': '221'},
 {'abrv': 'EIU',
  'conference': 'OVC',
  'division': None,
  'first_name': 'Eastern Illinois',
  'last_name': 'Panthers',
  'primary_color': '002951',
  'secondary_color': '009ffb',
  'team_id': '120'},
 {'abrv': 'WCU',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Western Carolina',
  'last_name': 'Catamounts',
  'primary_color': '592c88',
  'secondary_color': 'c1a875',
  'team_id': '179'},
 {'abrv': 'UCA',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Central Arkansas',
  'last_name': 'Bears',
  'primary_color': '3A1769',
  'secondary_color': 'D1D2D4',
  'team_id': '268'},
 {'abrv': 'MORG',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'Morgan State',
  'last_name': 'Bears',
  'primary_color': '011D4D',
  'secondary_color': 'EF5423',
  'team_id': '147'},
 {'abrv': 'FUR',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Furman',
  'last_name': 'Paladins',
  'primary_color': '201547',
  'secondary_color': '582c83',
  'team_id': '174'},
 {'abrv': 'ALCN',
  'conference': 'SWAC',
  'division': 'East Division',
  'first_name': 'Alcorn State',
  'last_name': 'Braves',
  'primary_color': '581E5E',
  'secondary_color': 'C1B565',
  'team_id': '188'},
 {'abrv': 'SFA',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Stephen F. Austin',
  'last_name': 'Lumberjacks',
  'primary_color': '340065',
  'secondary_color': 'CF0F0F',
  'team_id': '186'},
 {'abrv': 'W&M',
  'conference': 'CAA',
  'division': None,
  'first_name': 'William & Mary',
  'last_name': 'Tribe',
  'primary_color': '00523e',
  'secondary_color': 'ddd19f',
  'team_id': '200'},
 {'abrv': 'RMU',
  'conference': 'NEC',
  'division': None,
  'first_name': 'Robert Morris',
  'last_name': 'Colonials',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '217'},
 {'abrv': 'CIT',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'Citadel',
  'last_name': 'Bulldogs',
  'primary_color': '3975b7',
  'secondary_color': '1f3a60',
  'team_id': '172'},
 {'abrv': 'PRST',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Portland State',
  'last_name': 'Vikings',
  'primary_color': '154734',
  'secondary_color': 'ffffff',
  'team_id': '257'},
 {'abrv': 'MCNS',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'McNeese',
  'last_name': 'Cowboys',
  'primary_color': '1C4887',
  'secondary_color': 'F8D734',
  'team_id': '180'},
 {'abrv': 'RICH',
  'conference': 'CAA',
  'division': None,
  'first_name': 'Richmond',
  'last_name': 'Spiders',
  'primary_color': '000066',
  'secondary_color': '990000',
  'team_id': '198'},
 {'abrv': 'SHSU',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Sam Houston State',
  'last_name': 'Bearkats',
  'primary_color': 'F99138',
  'secondary_color': '010F8A',
  'team_id': '184'},
 {'abrv': 'CP',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Cal Poly',
  'last_name': 'Mustangs',
  'primary_color': '014B42',
  'secondary_color': 'ffe395',
  'team_id': '108'},
 {'abrv': 'NICH',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'Nicholls',
  'last_name': 'Colonels',
  'primary_color': 'CC0001',
  'secondary_color': 'C7C7C5',
  'team_id': '181'},
 {'abrv': 'HC',
  'conference': 'PATR',
  'division': None,
  'first_name': 'Holy Cross',
  'last_name': 'Crusaders',
  'primary_color': '602d89',
  'secondary_color': 'ffffff',
  'team_id': '162'},
 {'abrv': 'UNH',
  'conference': 'CAA',
  'division': None,
  'first_name': 'New Hampshire',
  'last_name': 'Wildcats',
  'primary_color': '041e42',
  'secondary_color': 'bbbcbc',
  'team_id': '205'},
 {'abrv': 'NAU',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'Northern Arizona',
  'last_name': 'Lumberjacks',
  'primary_color': '003466',
  'secondary_color': 'ffd200',
  'team_id': '118'},
 {'abrv': 'NORF',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'Norfolk State',
  'last_name': 'Spartans',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '233'},
 {'abrv': 'GRAM',
  'conference': 'SWAC',
  'division': 'West Division',
  'first_name': 'Grambling State',
  'last_name': 'Tigers',
  'primary_color': 'e1ad25',
  'secondary_color': '000000',
  'team_id': '189'},
 {'abrv': 'SDSU',
  'conference': 'MVC',
  'division': None,
  'first_name': 'South Dakota State',
  'last_name': 'Jackrabbits',
  'primary_color': '0033a0',
  'secondary_color': 'ffd100',
  'team_id': '312'},
 {'abrv': 'SCST',
  'conference': 'MEAC',
  'division': None,
  'first_name': 'South Carolina State',
  'last_name': 'Bulldogs',
  'primary_color': '6e1122',
  'secondary_color': '223155',
  'team_id': '149'},
 {'abrv': 'INST',
  'conference': 'MVC',
  'division': None,
  'first_name': 'Indiana State',
  'last_name': 'Sycamores',
  'primary_color': '0142bc',
  'secondary_color': 'FFFFFF',
  'team_id': '122'},
 {'abrv': 'MURR',
  'conference': 'OVC',
  'division': None,
  'first_name': 'Murray State',
  'last_name': 'Racers',
  'primary_color': '082e55',
  'secondary_color': 'f7c025',
  'team_id': '154'},
 {'abrv': 'UCD',
  'conference': 'BSKY',
  'division': None,
  'first_name': 'UC Davis',
  'last_name': 'Aggies',
  'primary_color': '002855',
  'secondary_color': 'b3a369',
  'team_id': '263'},
 {'abrv': 'IW',
  'conference': 'SLAND',
  'division': None,
  'first_name': 'UIW',
  'last_name': 'Cardinals',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2539'},
 {'abrv': 'ETSU',
  'conference': 'SOUTH',
  'division': None,
  'first_name': 'ETSU',
  'last_name': 'Buccaneers',
  'primary_color': '041e42',
  'secondary_color': 'ffc72c',
  'team_id': '173'}]


################################################################################
################################################################################


class NCAAFDB(DB):

    _abrv = "ncaaf"

    _schema = ("""
                    CREATE TABLE games (
                        game_id INT PRIMARY KEY,
                        home_id INT NOT NULL,
                        away_id INT NOT NULL,
                        winner_id INT NOT NULL,
                        loser_id INT NOT NULL,
                        game_type TEXT NOT NULL,
                        season INT NOT NULL,
                        week INT NOT NULL,
                        game_year INT NOT NULL,
                        game_date REAL NOT NULL,
                        game_time TEXT NOT NULL,
                        FOREIGN KEY (home_id) REFERENCES teams (team_id),
                        FOREIGN KEY (away_id) REFERENCES teams (team_id),
                        FOREIGN KEY (winner_id) REFERENCES teams (team_id),
                        FOREIGN KEY (loser_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE INDEX idx_season_date ON games (season, week)
                """,
                """
                    CREATE TABLE players (
                        player_id INT PRIMARY KEY,
                        first_name TEXT,
                        last_name TEXT,
                        height INT,
                        weight INT,
                        year INT,
                        pos_id INT,
                        team_id INT,
                        uni_num INT,
                        FOREIGN KEY (pos_id) REFERENCES position_types (pos_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE INDEX idx_names ON players (last_name, first_name)
                """,
                """
                    CREATE TABLE teams (
                        team_id INT PRIMARY KEY,
                        abrv TEXT,
                        first_name TEXT,
                        last_name TEXT,
                        conference TEXT,
                        division TEXT,
                        primary_color TEXT,
                        secondary_color TEXT
                    )
                """,
                """
                    CREATE TABLE lineups (
                        player_id INT NOT NULL,
                        game_id INT  NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        PRIMARY KEY (player_id, game_id),
                        FOREIGN KEY (player_id) REFERENCES players (player_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE TABLE player_stats (
                        player_stat_id INT PRIMARY KEY,
                        game_id INT NOT NULL,
                        player_id INT NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        stat_id INT NOT NULL,
                        value REAL NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (player_id) REFERENCES players (player_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stat_id) REFERENCES stat_types (stat_id)
                    )
                """,
                """
                    CREATE INDEX idx_player_stats ON player_stats (player_id, game_id, stat_id)
                """,
                """
                    CREATE TABLE team_stats (
                        team_stat_id INT PRIMARY KEY,
                        game_id INT NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        stat_id INT NOT NULL,
                        value REAL NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stat_id) REFERENCES stat_types (stat_id)
                    )
                """,
                """
                    CREATE INDEX idx_team_stats ON team_stats (team_id, game_id, stat_id)
                """,
                """
                    CREATE TABLE stat_types (
                        stat_id INT PRIMARY KEY,
                        title TEXT NOT NULL,
                        abrv TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE positions (
                        pos_id INT PRIMARY KEY,
                        title TEXT NOT NULL,
                        abrv TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE game_lines (
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        game_id INT NOT NULL,
                        spread REAL NOT NULL,
                        line INT NOT NULL,
                        money INT NOT NULL,
                        result INT NOT NULL,
                        spread_outcome INT NOT NULL,
                        money_outcome INT NOT NULL,
                        PRIMARY KEY (team_id, game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id)
                    )
                """,
                """
                    CREATE TABLE over_unders (
                        game_id INT PRIMARY Key,
                        ou REAL NOT NULL,
                        over_line REAL NOT NULL,
                        under_line REAL NOT NULL,
                        total INT NOT NULL,
                        outcome INT NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id)
                    )
                """,
                """
                    CREATE TABLE line_track (
                        book_name TEXT NOT NULL,
                        game_id INT NOT NULL,
                        away_spread REAL NOT NULL,
                        home_spread REAL NOT NULL,
                        away_line INT,
                        home_line INT,
                        away_ml INT,
                        home_ml INT,
                        total REAL,
                        over_line REAL,
                        under_line REAL,
                        timestamp REAL NOT NULL,
                        PRIMARY KEY (game_id, book_name, timestamp)
                    )
                """
    )

    def __init__(self):
        super().__init__(DB._dbPath.format(self._abrv))


    def insertGame(self, gameInfo):


        #### Add game info
        gameData = gameInfo["gameData"]
        gameId = yId(gameData["gameid"])
        homeId = yId(gameData["home_team_id"])
        awayId = yId(gameData["away_team_id"])

        awayPoints = gameData["total_away_points"]
        homePoints = gameData["total_home_points"]

        winnerId = yId(gameData.get("winning_team_id", -1))
        if winnerId == awayId:
            loserId = homeId
        elif winnerId == homeId:
            loserId = awayId
        else:
            loserId = -1
        season = gameData["season"]
        week = gameData["week_number"]
        gameType = yId(gameData["season_phase_id"])
        gameTime = gameData["start_time"]
        dt = datetime.datetime.strptime(gameData["start_time"], "%a, %d %b %Y %H:%M:%S %z") - datetime.timedelta(hours=5)
        gameYear = dt.year
        gameDate = float("{1}.{2}".format(*str(dt.date()).split("-")))

        self.insert("games", values=[gameId, homeId, awayId, winnerId, loserId,
                                            gameType, season, week, gameYear, gameDate, gameTime])

        ### Lineups Table
        lineups = {}
        for abrv, teamId in (("home", homeId), ("away", awayId)):
            oppId = homeId if teamId == awayId else awayId
            lineups[abrv] = []
            try:
                for player in gameData["lineups"]["{}_lineup".format(abrv)]["all"].values():
                    try:
                        self.insert("lineups", values=[yId(player["player_id"]), gameId, teamId, oppId])
                        lineups[abrv].append(yId(player["player_id"]))
                    except IntegrityError:
                        continue
            except (TypeError, KeyError):
                pass


        ### Player Stats

        for key, value in gameInfo["statsData"]["playerStats"].items():
            playerId = yId(key)

            if playerId in lineups["home"]:
                teamId = homeId
                oppId = awayId
            elif playerId in lineups["away"]:
                teamId = awayId
                oppId = homeId
            else:
                teamId = -1
                oppId = -1

            for statId, stat in [(yId(k), v) for k, v in value['ncaaf.stat_variation.2'].items()]:
                if self.checkEntry("stat_types", statId):
                    self.insert("player_stats", values=[None, gameId, playerId, teamId, oppId, statId, stat])


        ### Team Stats

        try:
            self.insert("team_stats", values=[None, gameId, homeId, awayId, 963, homePoints])
            self.insert("team_stats", values=[None, gameId, awayId, homeId, 963, awayPoints])
        except:
            pass

        try:

            teamStats = gameInfo["statsData"]["teamStatsByGameId"]["ncaaf.g.{}".format(gameId)]
            for teamId, values in [(yId(key), value['ncaaf.stat_variation.2'].items()) for key, value in teamStats.items()]:
                oppId = homeId if teamId == awayId else awayId

                for statId, stat in [(yId(key), item) for key, item in values]:
                    if self.checkEntry("stat_types", statId):
                        if statId == '935':
                            try:
                                mins,secs = stat.split(":")
                            except:
                                mins = -1; secs = 0
                            secs = int((int(secs)/60)*100)
                            stat = "{}.{}".format(mins,secs)
                        self.insert("team_stats", values=[None, gameId, teamId, oppId, statId, stat])
                    elif statId == '941':
                        try:
                            comp,att = stat.split("-")
                        except:
                            comp = -1; att = -1

                        self.insert("team_stats", values=[None, gameId, teamId, oppId, 939, att])
                        self.insert("team_stats", values=[None, gameId, teamId, oppId, 940, comp])
                    elif statId == '944':
                        try:
                            comp,att = stat.split("-")
                        except:
                            comp = -1; att = -1

                        self.insert("team_stats", values=[None, gameId, teamId, oppId, 942, att])
                        self.insert("team_stats", values=[None, gameId, teamId, oppId, 943, comp])
                    elif statId == '951':
                        try:
                            comp,att = stat.split("-")
                        except:
                            comp = -1; att = -1

                        self.insert("team_stats", values=[None, gameId, teamId, oppId, 954, att])
                        self.insert("team_stats", values=[None, gameId, teamId, oppId, 953, comp])
        except KeyError:
            pass


        #### Add Odds

        # try:
        gameData = gameInfo["gameData"]

        try:
            key = [x for x in gameData["odds"].keys()][0]
        except KeyError:
            key = ""

        teams = []
        for hA in ("away", "home"):
            teamId = yId(gameData["{}_team_id".format(hA)])
            oppId = homeId if teamId == awayId else awayId
            try:
                teamScore = int(gameData["total_{}_points".format(hA)])
            except:
                teamScore = -1

            try:
                teamSpread = float(gameData["odds"][key]["{}_spread".format(hA)])
            except:
                teamSpread = 0

            try:
                teamMoney = gameData["odds"][key]["{}_ml".format(hA)]
            except:
                teamMoney = 0

            try:
                teamVig = float(gameData["odds"][key]["{}_line".format(hA)])
            except:
                teamVig = 0

            teams.append(dict(zip(("Id", "Score", "Spread", "Money", "Vig"), (teamId, teamScore, teamSpread, teamMoney, teamVig))))

        #### overUndersTable

        try:
            ou = float(gameData["odds"][key]["total"])
        except:
            ou = 0

        try:
            overLine = int(gameData["odds"][key]["over_line"])
        except:
            overLine = 0

        try:
            underLine = int(gameData["odds"][key]["under_line"])
        except:
            underLine = 0

        total = teams[0]["Score"] + teams[1]["Score"]
        outcome = 0
        if total - ou > 0:
            outcome = 1
        elif total - ou < 0:
            outcome = -1
        self.insert("over_unders", values=[gameId, ou, overLine, underLine, total, outcome])


        #### gameLInesTable

        for i in range(2):
            team, opp = teams[-1*i], teams[1+(-1*i)]

            teamId = team["Id"]
            oppId = opp["Id"]
            spread = team["Spread"]
            line = team["Vig"]
            money = team["Money"]
            result = team["Score"] - opp["Score"]
            spreadOutcome = 0
            if result + spread > 0:
                spreadOutcome = 1
            elif result + spread < 0:
                spreadOutcome = -1
            moneyOutcome = 0
            if result > 0:
                moneyOutcome = 1
            elif result < 0:
                moneyOutcome = -1



            self.insert("game_lines", values=(teamId, oppId, gameId,
                                                      spread, line, money, result,
                                                          spreadOutcome, moneyOutcome))


    def insertPlayer(self, info):
        playerId = yId(info["player_id"])
        firstName = info["first_name"]
        lastName = info["last_name"]

        # try:
        #     year = info["bio"]["college_experience"]["experience_name"]
        # except KeyError:
        #     year = info["bio"]["experience"]
        posId = yId(info["primary_position_id"])
        teamId = yId(info["team_id"])
        uniNum = info["uniform_number"]

        self.insert("players", values=(playerId, firstName, lastName, -1, -1, -1,
                                        posId, teamId, uniNum))


    def seed(self):

        for info in statTypes:
            self.insert("stat_types", info=info)

        for info in positionTypes:
            self.insert("positions", info=info)

        for team in teams:
            self.insert("teams", info=team)

        self.insertPlayers()
        self.insertBoxScores()


    def unknownPlayers(self):
        pass
        # cmd = """
        #         SELECT DISTINCT player_id
        #             FROM player_stats
        #             INNER JOIN games
        #                 ON player_stats.game_id = games.game_id
        #             WHERE season = 2021 AND player_id NOT IN (SELECT player_id FROM players)
        #         """
        # return [x[0] for x in self.fetchAll(cmd)]



################################################################################
################################################################################


class NCAAFMatchDB(DB):

    _abrv = "ncaaf"

    _schema = ("""
                    CREATE TABLE games (
                        game_id INT PRIMARY KEY,
                        home_id INT NOT NULL,
                        away_id INT NOT NULL,
                        winner_id INT NOT NULL,
                        loser_id INT NOT NULL,
                        game_type TEXT NOT NULL,
                        season INT NOT NULL,
                        week INT NOT NULL,
                        game_year INT NOT NULL,
                        game_date REAL NOT NULL,
                        game_time TEXT NOT NULL,
                        FOREIGN KEY (home_id) REFERENCES teams (team_id),
                        FOREIGN KEY (away_id) REFERENCES teams (team_id),
                        FOREIGN KEY (winner_id) REFERENCES teams (team_id),
                        FOREIGN KEY (loser_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE INDEX idx_season_date ON games (season, week)
                """,
                """
                    CREATE TABLE players (
                        player_id INT PRIMARY KEY,
                        first_name TEXT,
                        last_name TEXT,
                        height INT,
                        weight INT,
                        year INT,
                        pos_id INT,
                        team_id INT,
                        uni_num INT,
                        FOREIGN KEY (pos_id) REFERENCES position_types (pos_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE INDEX idx_names ON players (last_name, first_name)
                """,
                """
                    CREATE TABLE teams (
                        team_id INT PRIMARY KEY,
                        abrv TEXT,
                        first_name TEXT,
                        last_name TEXT,
                        conference TEXT,
                        division TEXT,
                        primary_color TEXT,
                        secondary_color TEXT
                    )
                """,
                """
                    CREATE TABLE lineups (
                        player_id INT NOT NULL,
                        game_id INT  NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        PRIMARY KEY (player_id, game_id),
                        FOREIGN KEY (player_id) REFERENCES players (player_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE TABLE player_stats (
                        player_stat_id INT PRIMARY KEY,
                        game_id INT NOT NULL,
                        player_id INT NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        stat_id INT NOT NULL,
                        value REAL NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (player_id) REFERENCES players (player_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stat_id) REFERENCES stat_types (stat_id)
                    )
                """,
                """
                    CREATE INDEX idx_player_stats ON player_stats (player_id, game_id, stat_id)
                """,
                """
                    CREATE TABLE team_stats (
                        team_stat_id INT PRIMARY KEY,
                        game_id INT NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        stat_id INT NOT NULL,
                        value REAL NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stat_id) REFERENCES stat_types (stat_id)
                    )
                """,
                """
                    CREATE INDEX idx_team_stats ON team_stats (team_id, game_id, stat_id)
                """,
                """
                    CREATE TABLE stat_types (
                        stat_id INT PRIMARY KEY,
                        title TEXT NOT NULL,
                        abrv TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE positions (
                        pos_id INT PRIMARY KEY,
                        title TEXT NOT NULL,
                        abrv TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE game_lines (
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        game_id INT NOT NULL,
                        spread REAL NOT NULL,
                        line INT NOT NULL,
                        money INT NOT NULL,
                        result INT NOT NULL,
                        spread_outcome INT NOT NULL,
                        money_outcome INT NOT NULL,
                        PRIMARY KEY (team_id, game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id)
                    )
                """,
                """
                    CREATE TABLE over_unders (
                        game_id INT PRIMARY Key,
                        ou REAL NOT NULL,
                        over_line REAL NOT NULL,
                        under_line REAL NOT NULL,
                        total INT NOT NULL,
                        outcome INT NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id)
                    )
                """,
                """
                    CREATE TABLE line_track (
                        book_name TEXT NOT NULL,
                        game_id INT NOT NULL,
                        away_spread REAL NOT NULL,
                        home_spread REAL NOT NULL,
                        away_line INT,
                        home_line INT,
                        away_ml INT,
                        home_ml INT,
                        total REAL,
                        over_line REAL,
                        under_line REAL,
                        timestamp REAL NOT NULL,
                        PRIMARY KEY (game_id, book_name, timestamp)
                    )
                """
    )

    def __init__(self, matchPath):
        super().__init__(matchPath)


    def insertGame(self, gameInfo):
        pass






    def seed(self):

        for info in statTypes:
            self.insert("stat_types", info=info)

        for info in positionTypes:
            self.insert("positions", info=info)

        for team in teams:
            self.insert("teams", info=team)


    def unknownPlayers(self):
        pass
        # cmd = """
        #         SELECT DISTINCT player_id
        #             FROM player_stats
        #             INNER JOIN games
        #                 ON player_stats.game_id = games.game_id
        #             WHERE season = 2021 AND player_id NOT IN (SELECT player_id FROM players)
        #         """
        # return [x[0] for x in self.fetchAll(cmd)]
