import os
import shutil
import tarfile
import json
import datetime
import math

from .Database import Database as DB, yId, normal
from ..Utils import SQL

from pprint import pprint



positions = [{'abrv': 'M', 'pos_id': '4', 'title': 'Midfielder'},
 {'abrv': 'F', 'pos_id': '3', 'title': 'Forward'},
 {'abrv': 'D', 'pos_id': '5', 'title': 'Defender'},
 {'abrv': 'G', 'pos_id': '2', 'title': 'Goalkeeper'},
 {'abrv': 'S', 'pos_id': '12', 'title': 'Striker'},
 {'abrv': '-', 'pos_id': '15', 'title': 'Substitute',}
 ]


statTypes = [{'abrv': 'GK', 'stat_id': '210', 'title': 'Goals Kicks'},
 {'abrv': 'PA', 'stat_id': '331', 'title': 'Pass Accuracy'},
 {'abrv': 'STA', 'stat_id': '2', 'title': 'Games Started'},
 {'abrv': 'TS', 'stat_id': '321', 'title': 'Tackle success'},
 {'abrv': 'Y', 'stat_id': '3', 'title': 'Yellows'},
 {'abrv': 'A', 'stat_id': '102', 'title': 'Assists'},
 {'abrv': 'R', 'stat_id': '4', 'title': 'Reds'},
 {'abrv': 'SHO', 'stat_id': '103', 'title': 'Shots'},
 {'abrv': 'PEN', 'stat_id': '5', 'title': 'Penalties'},
 {'abrv': 'SOG', 'stat_id': '313', 'title': 'Shots (On goal)'},
 {'abrv': 'SHOG', 'stat_id': '104', 'title': 'Shots on Goal'},
 {'abrv': 'FC', 'stat_id': '6', 'title': 'Fouls Conceded'},
 {'abrv': 'TA', 'stat_id': '501', 'title': 'Tackles'},
 {'abrv': 'TOP', 'stat_id': '314', 'title': 'Possession'},
 {'abrv': 'SAV', 'stat_id': '204', 'title': 'Saves'},
 {'abrv': 'Goals+Assists', 'stat_id': '920', 'title': 'Sum of Goals and Assists'},
 {'abrv': 'FS', 'stat_id': '7', 'title': 'Fouls Suffered'},
 {'abrv': 'CLR', 'stat_id': '502', 'title': 'Clearances'},
 {'abrv': 'Shots', 'stat_id': '304', 'title': 'Shots'},
 {'abrv': 'FC', 'stat_id': '315', 'title': 'Fouls Committed'},
 {'abrv': 'SUB', 'stat_id': '8', 'title': 'Substitutes'},
 {'abrv': 'SAV', 'stat_id': '305', 'title': 'Saves'},
 {'abrv': 'Offsides', 'stat_id': '316', 'title': 'Offsides'},
 {'abrv': 'FK', 'stat_id': '107', 'title': 'Free Kicks'},
 {'abrv': 'G', 'stat_id': '9', 'title': 'Goals'},
 {'abrv': 'Corner', 'stat_id': '317', 'title': 'Corner Kicks'},
 {'abrv': 'PAS', 'stat_id': '108', 'title': 'Passes'},
 {'abrv': 'COR', 'stat_id': '109', 'title': 'Corners'},
 {'abrv': 'GC', 'stat_id': '209', 'title': 'Goals Conceded'},
 {'abrv': 'Mins', 'stat_id': '10', 'title': 'Minutes'},
 {'abrv': 'Form', 'stat_id': '400', 'title': 'Formation'}]


leagues = [{'league_id': 'fbde', 'title': 'Bundesliga'},
             {'league_id': 'fbfacup', 'title': 'FA Cup'},
             {'league_id': 'fbes', 'title': 'La Liga'},
             {'league_id': 'fbeuropa', 'title': 'Europa League'},
             {'league_id': 'fbcopadelrey', 'title': 'Copa Del Ray'},
             {'league_id': 'fbchampions', 'title': 'Champions League'},
             {'league_id': 'fbit', 'title': 'Serie A'},
             {'league_id': 'fbleaguecup', 'title': 'League Cup'},
             {'league_id': 'fbgb', 'title': 'Premier League'},
             {'league_id': 'mls', 'title': 'Major League Soccer'},
             {'league_id': 'fbcoppait', 'title': 'Italian Cup'},
             {'league_id': 'fbdfbpokal', 'title': 'DFB Pokal'},
             {'league_id': 'fbeusc', 'title': 'European Super Cup'},
             {'league_id': 'fbesspcopa', 'title': 'Spanish Super Cup'},
             {'league_id': 'fbcomshield', 'title': 'Community Shield'},
             {'league_id': 'fbigus', 'title': 'MLS All-Star Game'}]


teams = [{'abrv': 'CHI',
  'name': 'Chicago Fire',
  'primary_color': '16275a',
  'secondary_color': 'b3272d',
  'team_id': '41',
  'url': 'https://sports.yahoo.com/soccer/teams/chicago-fire/'},
 {'abrv': 'LAFC',
  'name': 'Los Angeles Football Club',
  'primary_color': '000000',
  'secondary_color': 'c39e6d',
  'team_id': '5204',
  'url': 'https://sports.yahoo.com/soccer/teams/los-angeles-football-club/'},
 {'abrv': 'BRE',
  'name': 'SV Werder Bremen',
  'primary_color': '00944b',
  'secondary_color': 'f3f3f3',
  'team_id': '115',
  'url': 'https://sports.yahoo.com/soccer/teams/sv-werder-bremen/'},
 {'abrv': 'WAT',
  'name': 'Watford',
  'primary_color': 'fbee23',
  'secondary_color': 'ed2127',
  'team_id': '138',
  'url': 'https://sports.yahoo.com/soccer/teams/watford/'},
 {'abrv': 'UDI',
  'name': 'Udinese',
  'primary_color': 'F1D141',
  'secondary_color': '',
  'team_id': '19',
  'url': 'https://sports.yahoo.com/soccer/teams/udinese/'},
 {'abrv': 'BSC',
  'name': 'Hertha BSC',
  'primary_color': '004ca4',
  'secondary_color': 'f3f3f3',
  'team_id': '113',
  'url': 'https://sports.yahoo.com/soccer/teams/hertha-bsc/'},
 {'abrv': 'VAL',
  'name': 'Valencia CF',
  'primary_color': 'ffffff',
  'secondary_color': 'f47920',
  'team_id': '39',
  'url': 'https://sports.yahoo.com/soccer/teams/valencia-cf/'},
 {'abrv': 'ORL',
  'name': 'Orlando City SC',
  'primary_color': '61259E',
  'secondary_color': 'FFE293',
  'team_id': '1623',
  'url': 'https://sports.yahoo.com/soccer/teams/orlando-city-sc/'},
 {'abrv': 'LEV',
  'name': 'Levante',
  'primary_color': '0b2049',
  'secondary_color': 'e02130',
  'team_id': '30',
  'url': 'https://sports.yahoo.com/soccer/teams/levante/'},
 {'abrv': 'ATH',
  'name': 'Athletic Club',
  'primary_color': 'ffffff',
  'secondary_color': 'e0092c',
  'team_id': '22',
  'url': 'https://sports.yahoo.com/soccer/teams/athletic-club/'},
 {'abrv': 'BRN',
  'name': 'Burnley',
  'primary_color': '6c1d45',
  'secondary_color': '99d6ea',
  'team_id': '143',
  'url': 'https://sports.yahoo.com/soccer/teams/burnley/'},
 {'abrv': 'LA',
  'name': 'LA Galaxy',
  'primary_color': '0065a4',
  'secondary_color': '00245d',
  'team_id': '48',
  'url': 'https://sports.yahoo.com/soccer/teams/la-galaxy/'},
 {'abrv': 'DAL',
  'name': 'FC Dallas',
  'primary_color': 'd11241',
  'secondary_color': '003e7e',
  'team_id': '46',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-dallas/'},
 {'abrv': 'GEN',
  'name': 'Genoa',
  'primary_color': 'DA2935',
  'secondary_color': '',
  'team_id': '7',
  'url': 'https://sports.yahoo.com/soccer/teams/genoa/'},
 {'abrv': 'CHE',
  'name': 'Chelsea',
  'primary_color': '034694',
  'secondary_color': 'ee242c',
  'team_id': '83',
  'url': 'https://sports.yahoo.com/soccer/teams/chelsea/'},
 {'abrv': 'PTI',
  'name': 'Portland Timbers',
  'primary_color': 'cb9700',
  'secondary_color': '0d421d',
  'team_id': '53',
  'url': 'https://sports.yahoo.com/soccer/teams/portland-timbers/'},
 {'abrv': 'RSO',
  'name': 'Real Sociedad',
  'primary_color': 'ffffff',
  'secondary_color': '0058b1',
  'team_id': '36',
  'url': 'https://sports.yahoo.com/soccer/teams/real-sociedad/'},
 {'abrv': 'GRA',
  'name': 'Granada CF',
  'primary_color': 'a61b2b',
  'secondary_color': 'ffffff',
  'team_id': '29',
  'url': 'https://sports.yahoo.com/soccer/teams/granada-cf/'},
 {'abrv': 'RMA',
  'name': 'Real Madrid',
  'primary_color': 'ffffff',
  'secondary_color': '0255a5',
  'team_id': '35',
  'url': 'https://sports.yahoo.com/soccer/teams/real-madrid/'},
 {'abrv': 'AFC',
  'name': 'Bournemouth',
  'primary_color': 'da291c',
  'secondary_color': 'b50e12',
  'team_id': '206',
  'url': 'https://sports.yahoo.com/soccer/teams/bournemouth/'},
 {'abrv': 'BOL',
  'name': 'Bologna',
  'primary_color': 'EC4336',
  'secondary_color': '',
  'team_id': '2',
  'url': 'https://sports.yahoo.com/soccer/teams/bologna/'},
 {'abrv': 'SKC',
  'name': 'Sporting Kansas City',
  'primary_color': '93b1d7',
  'secondary_color': '002a5c',
  'team_id': '57',
  'url': 'https://sports.yahoo.com/soccer/teams/sporting-kansas-city/'},
 {'abrv': 'SCF',
  'name': 'Sport-Club Freiburg',
  'primary_color': 'cc3333',
  'secondary_color': '101010',
  'team_id': '114',
  'url': 'https://sports.yahoo.com/soccer/teams/sport-club-freiburg/'},
 {'abrv': 'SEV',
  'name': 'Sevilla',
  'primary_color': 'ffffff',
  'secondary_color': 'cd0a33',
  'team_id': '38',
  'url': 'https://sports.yahoo.com/soccer/teams/sevilla/'},
 {'abrv': 'WOB',
  'name': 'VfL Wolfsburg',
  'primary_color': '64b42d',
  'secondary_color': '2b353e',
  'team_id': '117',
  'url': 'https://sports.yahoo.com/soccer/teams/vfl-wolfsburg/'},
 {'abrv': 'VLD',
  'name': 'Real Valladolid',
  'primary_color': '931b89',
  'secondary_color': 'ffffff',
  'team_id': '37',
  'url': 'https://sports.yahoo.com/soccer/teams/real-valladolid/'},
 {'abrv': 'TOR',
  'name': 'Toronto FC',
  'primary_color': 'ab1e2d',
  'secondary_color': '3f4743',
  'team_id': '58',
  'url': 'https://sports.yahoo.com/soccer/teams/toronto-fc/'},
 {'abrv': 'VAN',
  'name': 'Vancouver Whitecaps',
  'primary_color': '04265c',
  'secondary_color': '94c2e4',
  'team_id': '59',
  'url': 'https://sports.yahoo.com/soccer/teams/vancouver-whitecaps/'},
 {'abrv': 'NE',
  'name': 'New England Revolution',
  'primary_color': 'e51938',
  'secondary_color': '002b5c',
  'team_id': '50',
  'url': 'https://sports.yahoo.com/soccer/teams/new-england-revolution/'},
 {'abrv': 'CLB',
  'name': 'Columbus Crew',
  'primary_color': 'fef200',
  'secondary_color': '231f20',
  'team_id': '44',
  'url': 'https://sports.yahoo.com/soccer/teams/columbus-crew/'},
 {'abrv': 'VER',
  'name': 'Verona',
  'primary_color': 'CFA105',
  'secondary_color': '',
  'team_id': '20',
  'url': 'https://sports.yahoo.com/soccer/teams/verona/'},
 {'abrv': 'JUV',
  'name': 'Juventus',
  'primary_color': 'F5B400',
  'secondary_color': '',
  'team_id': '9',
  'url': 'https://sports.yahoo.com/soccer/teams/juventus/'},
 {'abrv': 'MCI',
  'name': 'Manchester City',
  'primary_color': '6cabdd',
  'secondary_color': '1c2c5b',
  'team_id': '89',
  'url': 'https://sports.yahoo.com/soccer/teams/manchester-city/'},
 {'abrv': 'MIN',
  'name': 'Minnesota United FC',
  'primary_color': '585958',
  'secondary_color': 'D8DAD9',
  'team_id': '4261',
  'url': 'https://sports.yahoo.com/soccer/teams/minnesota-united-fc/'},
 {'abrv': 'PHI',
  'name': 'Philadelphia Union',
  'primary_color': '002d55',
  'secondary_color': '5090cd',
  'team_id': '52',
  'url': 'https://sports.yahoo.com/soccer/teams/philadelphia-union/'},
 {'abrv': 'SHU',
  'name': 'Sheffield United',
  'primary_color': 'bb0000',
  'secondary_color': '333333',
  'team_id': '131',
  'url': 'https://sports.yahoo.com/soccer/teams/sheffield-united/'},
 {'abrv': 'CIN',
  'name': 'FC Cincinnati',
  'primary_color': 'fe5000',
  'secondary_color': '003087',
  'team_id': '6309',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-cincinnati/'},
 {'abrv': 'LAZ',
  'name': 'Lazio',
  'primary_color': '87D8F7',
  'secondary_color': '',
  'team_id': '10',
  'url': 'https://sports.yahoo.com/soccer/teams/lazio/'},
 {'abrv': 'SAM',
  'name': 'Sampdoria',
  'primary_color': '0089CA',
  'secondary_color': '',
  'team_id': '16',
  'url': 'https://sports.yahoo.com/soccer/teams/sampdoria/'},
 {'abrv': 'MUN',
  'name': 'Manchester United',
  'primary_color': 'da291c',
  'secondary_color': 'fbe122',
  'team_id': '90',
  'url': 'https://sports.yahoo.com/soccer/teams/manchester-united/'},
 {'abrv': 'MTL',
  'name': 'Montreal Impact',
  'primary_color': '2b63ad',
  'secondary_color': '28477d',
  'team_id': '49',
  'url': 'https://sports.yahoo.com/soccer/teams/montreal-impact/'},
 {'abrv': 'COL',
  'name': 'Colorado Rapids',
  'primary_color': '862633',
  'secondary_color': '8bb8e8',
  'team_id': '43',
  'url': 'https://sports.yahoo.com/soccer/teams/colorado-rapids/'},
 {'abrv': 'BRES',
  'name': 'Brescia',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '639',
  'url': 'https://sports.yahoo.com/soccer/teams/brescia/'},
 {'abrv': 'UNB',
  'name': '1. FC Union Berlin',
  'primary_color': 'd4011d',
  'secondary_color': 'f3f3f3',
  'team_id': '694',
  'url': 'https://sports.yahoo.com/soccer/teams/1-fc-union-berlin/'},
 {'abrv': 'SCP',
  'name': 'SC Paderborn 07',
  'primary_color': '005ca8',
  'secondary_color': '101010',
  'team_id': '703',
  'url': 'https://sports.yahoo.com/soccer/teams/sc-paderborn-07/'},
 {'abrv': 'PMA',
  'name': 'Parma',
  'primary_color': '2F73AC',
  'secondary_color': '',
  'team_id': '14',
  'url': 'https://sports.yahoo.com/soccer/teams/parma/'},
 {'abrv': 'NAP',
  'name': 'Napoli',
  'primary_color': '62B4E5',
  'secondary_color': '',
  'team_id': '13',
  'url': 'https://sports.yahoo.com/soccer/teams/napoli/'},
 {'abrv': 'LEI',
  'name': 'Leicester City',
  'primary_color': '003090',
  'secondary_color': 'fdbe11',
  'team_id': '123',
  'url': 'https://sports.yahoo.com/soccer/teams/leicester-city/'},
 {'abrv': 'EVE',
  'name': 'Everton',
  'primary_color': '003399',
  'secondary_color': 'ffffff',
  'team_id': '85',
  'url': 'https://sports.yahoo.com/soccer/teams/everton/'},
 {'abrv': 'NYR',
  'name': 'New York Red Bulls',
  'primary_color': 'e31351',
  'secondary_color': '002f65',
  'team_id': '51',
  'url': 'https://sports.yahoo.com/soccer/teams/new-york-red-bulls/'},
 {'abrv': 'HOF',
  'name': '1899 Hoffenheim',
  'primary_color': '0062be',
  'secondary_color': 'f3f3f3',
  'team_id': '102',
  'url': 'https://sports.yahoo.com/soccer/teams/1899-hoffenheim/'},
 {'abrv': 'MIA',
  'name': 'Inter Miami CF',
  'primary_color': 'f7b5cd',
  'secondary_color': '231f20',
  'team_id': '7263',
  'url': 'https://sports.yahoo.com/soccer/teams/inter-miami-cf/'},
 {'abrv': 'BAR',
  'name': 'Barcelona',
  'primary_color': 'a50044',
  'secondary_color': '004d98',
  'team_id': '24',
  'url': 'https://sports.yahoo.com/soccer/teams/barcelona/'},
 {'abrv': 'TNO',
  'name': 'Torino',
  'primary_color': '881F19',
  'secondary_color': '',
  'team_id': '18',
  'url': 'https://sports.yahoo.com/soccer/teams/torino/'},
 {'abrv': 'BHA',
  'name': 'Brighton and Hove Albion',
  'primary_color': '0057b8',
  'secondary_color': 'ffcd00',
  'team_id': '207',
  'url': 'https://sports.yahoo.com/soccer/teams/brighton-and-hove-albion/'},
 {'abrv': 'GET',
  'name': 'Getafe',
  'primary_color': '1f477f',
  'secondary_color': 'ffffff',
  'team_id': '28',
  'url': 'https://sports.yahoo.com/soccer/teams/getafe/'},
 {'abrv': 'BVB',
  'name': 'Borussia Dortmund',
  'primary_color': 'ffe600',
  'secondary_color': '323232',
  'team_id': '104',
  'url': 'https://sports.yahoo.com/soccer/teams/borussia-dortmund/'},
 {'abrv': 'NYC',
  'name': 'New York City FC',
  'primary_color': '6CACE4',
  'secondary_color': '041E42',
  'team_id': '1622',
  'url': 'https://sports.yahoo.com/soccer/teams/new-york-city-fc/'},
 {'abrv': 'RSL',
  'name': 'Real Salt Lake',
  'primary_color': 'b30838',
  'secondary_color': '013a81',
  'team_id': '54',
  'url': 'https://sports.yahoo.com/soccer/teams/real-salt-lake/'},
 {'abrv': 'ESP',
  'name': 'Espanyol',
  'primary_color': '1e6bc0',
  'secondary_color': 'ffffff',
  'team_id': '27',
  'url': 'https://sports.yahoo.com/soccer/teams/espanyol/'},
 {'abrv': 'ATM',
  'name': 'Atlético de Madrid',
  'primary_color': 'c63527',
  'secondary_color': '2c325f',
  'team_id': '23',
  'url': 'https://sports.yahoo.com/soccer/teams/atlético-de-madrid/'},
 {'abrv': 'ALV',
  'name': 'Alavés',
  'primary_color': 'ffffff',
  'secondary_color': '005eaa',
  'team_id': '711',
  'url': 'https://sports.yahoo.com/soccer/teams/alavés/'},
 {'abrv': 'BET',
  'name': 'Real Betis',
  'primary_color': 'ffffff',
  'secondary_color': '009655',
  'team_id': '34',
  'url': 'https://sports.yahoo.com/soccer/teams/real-betis/'},
 {'abrv': 'ATL',
  'name': 'Atlanta United FC',
  'primary_color': '80000A',
  'secondary_color': '221f1f',
  'team_id': '4253',
  'url': 'https://sports.yahoo.com/soccer/teams/atlanta-united-fc/'},
 {'abrv': 'LECC',
  'name': 'Lecce',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '838',
  'url': 'https://sports.yahoo.com/soccer/teams/lecce/'},
 {'abrv': 'FFM',
  'name': 'Eintracht Frankfurt',
  'primary_color': 'f50000',
  'secondary_color': 'f3f3f3',
  'team_id': '107',
  'url': 'https://sports.yahoo.com/soccer/teams/eintracht-frankfurt/'},
 {'abrv': 'HOU',
  'name': 'Houston Dynamo',
  'primary_color': 'f4911e',
  'secondary_color': '92c3f1',
  'team_id': '47',
  'url': 'https://sports.yahoo.com/soccer/teams/houston-dynamo/'},
 {'abrv': 'SJ',
  'name': 'San Jose Earthquakes',
  'primary_color': '1f1f1f',
  'secondary_color': '30457a',
  'team_id': '55',
  'url': 'https://sports.yahoo.com/soccer/teams/san-jose-earthquakes/'},
 {'abrv': 'AUG',
  'name': 'FC Augsburg',
  'primary_color': '007E0D',
  'secondary_color': '',
  'team_id': '108',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-augsburg/'},
 {'abrv': 'LEG',
  'name': 'Leganés',
  'primary_color': '0957c3',
  'secondary_color': 'ffffff',
  'team_id': '741',
  'url': 'https://sports.yahoo.com/soccer/teams/leganés/'},
 {'abrv': 'CEL',
  'name': 'Celta de Vigo',
  'primary_color': '6cace4',
  'secondary_color': 'ffffff',
  'team_id': '25',
  'url': 'https://sports.yahoo.com/soccer/teams/celta-de-vigo/'},
 {'abrv': 'SAS',
  'name': 'Sassuolo',
  'primary_color': '13812E',
  'secondary_color': '',
  'team_id': '17',
  'url': 'https://sports.yahoo.com/soccer/teams/sassuolo/'},
 {'abrv': 'FIO',
  'name': 'Fiorentina',
  'primary_color': '420A92',
  'secondary_color': '',
  'team_id': '6',
  'url': 'https://sports.yahoo.com/soccer/teams/fiorentina/'},
 {'abrv': 'WHU',
  'name': 'West Ham United',
  'primary_color': '7C1E42',
  'secondary_color': '1bb1e7',
  'team_id': '99',
  'url': 'https://sports.yahoo.com/soccer/teams/west-ham-united/'},
 {'abrv': 'ATA',
  'name': 'Atalanta',
  'primary_color': '0071BC',
  'secondary_color': '',
  'team_id': '1',
  'url': 'https://sports.yahoo.com/soccer/teams/atalanta/'},
 {'abrv': 'SEA',
  'name': 'Seattle Sounders FC',
  'primary_color': '236192',
  'secondary_color': '658d1b',
  'team_id': '56',
  'url': 'https://sports.yahoo.com/soccer/teams/seattle-sounders-fc/'},
 {'abrv': 'ROM',
  'name': 'Roma',
  'primary_color': 'B30838',
  'secondary_color': '',
  'team_id': '15',
  'url': 'https://sports.yahoo.com/soccer/teams/roma/'},
 {'abrv': 'CAG',
  'name': 'Cagliari',
  'primary_color': 'D51B00',
  'secondary_color': '',
  'team_id': '3',
  'url': 'https://sports.yahoo.com/soccer/teams/cagliari/'},
 {'abrv': 'ARS',
  'name': 'Arsenal',
  'primary_color': 'ef0107',
  'secondary_color': 'db0007',
  'team_id': '80',
  'url': 'https://sports.yahoo.com/soccer/teams/arsenal/'},
 {'abrv': 'SOU',
  'name': 'Southampton',
  'primary_color': 'd71920',
  'secondary_color': '130c0e',
  'team_id': '93',
  'url': 'https://sports.yahoo.com/soccer/teams/southampton/'},
 {'abrv': 'ACM',
  'name': 'Milan',
  'primary_color': 'FB090B',
  'secondary_color': '',
  'team_id': '12',
  'url': 'https://sports.yahoo.com/soccer/teams/milan/'},
 {'abrv': 'EIB',
  'name': 'Eibar',
  'primary_color': 'ffffff',
  'secondary_color': 'af262c',
  'team_id': '728',
  'url': 'https://sports.yahoo.com/soccer/teams/eibar/'},
 {'abrv': 'M05',
  'name': '1. FSV Mainz 05',
  'primary_color': 'DA2D2E',
  'secondary_color': '',
  'team_id': '101',
  'url': 'https://sports.yahoo.com/soccer/teams/1-fsv-mainz-05/'},
 {'abrv': 'AVL',
  'name': 'Aston Villa',
  'primary_color': '660033',
  'secondary_color': 'ffe600',
  'team_id': '81',
  'url': 'https://sports.yahoo.com/soccer/teams/aston-villa/'},
 {'abrv': 'WOL',
  'name': 'Wolverhampton Wanderers',
  'primary_color': 'fdb913',
  'secondary_color': '231f20',
  'team_id': '140',
  'url': 'https://sports.yahoo.com/soccer/teams/wolverhampton-wanderers/'},
 {'abrv': 'NEW',
  'name': 'Newcastle United',
  'primary_color': '241f20',
  'secondary_color': 'f1be48',
  'team_id': '91',
  'url': 'https://sports.yahoo.com/soccer/teams/newcastle-united/'},
 {'abrv': 'SPAL',
  'name': 'SPAL',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2197',
  'url': 'https://sports.yahoo.com/soccer/teams/spal/'},
 {'abrv': 'VIL',
  'name': 'Villarreal',
  'primary_color': '1b1b1b',
  'secondary_color': 'ffe715',
  'team_id': '40',
  'url': 'https://sports.yahoo.com/soccer/teams/villarreal/'},
 {'abrv': 'INT',
  'name': 'Internazionale',
  'primary_color': '0055A0',
  'secondary_color': '',
  'team_id': '8',
  'url': 'https://sports.yahoo.com/soccer/teams/internazionale/'},
 {'abrv': 'OSA',
  'name': 'Osasuna',
  'primary_color': '2b2958',
  'secondary_color': 'b52830',
  'team_id': '32',
  'url': 'https://sports.yahoo.com/soccer/teams/osasuna/'},
 {'abrv': 'LIV',
  'name': 'Liverpool',
  'primary_color': 'c8102e',
  'secondary_color': '00b2a9',
  'team_id': '88',
  'url': 'https://sports.yahoo.com/soccer/teams/liverpool/'},
 {'abrv': 'MLL',
  'name': 'Mallorca',
  'primary_color': 'cc3333',
  'secondary_color': '000000',
  'team_id': '161',
  'url': 'https://sports.yahoo.com/soccer/teams/mallorca/'},
 {'abrv': 'DC',
  'name': 'D.C. United',
  'primary_color': 'ee1a39',
  'secondary_color': '231f20',
  'team_id': '45',
  'url': 'https://sports.yahoo.com/soccer/teams/dc-united/'},
 {'abrv': 'B04',
  'name': 'Bayer 04 Leverkusen',
  'primary_color': 'f70002',
  'secondary_color': '101010',
  'team_id': '103',
  'url': 'https://sports.yahoo.com/soccer/teams/bayer-04-leverkusen/'},
 {'abrv': 'CRY',
  'name': 'Crystal Palace',
  'primary_color': '1b458f',
  'secondary_color': 'a7a5a6',
  'team_id': '84',
  'url': 'https://sports.yahoo.com/soccer/teams/crystal-palace/'},
 {'abrv': 'S04',
  'name': 'FC Schalke 04',
  'primary_color': '004da3',
  'secondary_color': 'f3f3f3',
  'team_id': '110',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-schalke-04/'},
 {'abrv': 'TOT',
  'name': 'Tottenham Hotspur',
  'primary_color': '132257',
  'secondary_color': '',
  'team_id': '97',
  'url': 'https://sports.yahoo.com/soccer/teams/tottenham-hotspur/'},
 {'abrv': 'NOR',
  'name': 'Norwich City',
  'primary_color': 'fff200',
  'secondary_color': '00a651',
  'team_id': '92',
  'url': 'https://sports.yahoo.com/soccer/teams/norwich-city/'},
 {'abrv': 'RBL',
  'name': 'RB Leipzig',
  'primary_color': 'dd013f',
  'secondary_color': '06122b',
  'team_id': '789',
  'url': 'https://sports.yahoo.com/soccer/teams/rb-leipzig/'},
  {'abrv': 'LEE',
  'name': 'Leeds United',
  'primary_color': '005b9e',
  'secondary_color': 'fdcb00',
  'team_id': '122',
  'url': 'https://sports.yahoo.com/soccer/teams/leeds-united/'},
 {'abrv': 'FUL',
  'name': 'Fulham',
  'primary_color': 'cc0000',
  'secondary_color': '000000',
  'team_id': '86',
  'url': 'https://sports.yahoo.com/soccer/teams/fulham/'},
 {'abrv': 'WBA',
  'name': 'West Bromwich Albion',
  'primary_color': '223067',
  'secondary_color': 'ffffff',
  'team_id': '98',
  'url': 'https://sports.yahoo.com/soccer/teams/west-bromwich-albion/'},
 {'abrv': 'KAA',
  'name': 'KAA Gent',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1772',
  'url': 'https://sports.yahoo.com/soccer/teams/kaa-gent/'},
 {'abrv': 'RIG',
  'name': 'Riga FC',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '5722',
  'url': 'https://sports.yahoo.com/soccer/teams/riga-fc/'},
 {'abrv': 'DJU',
  'name': 'Djurgårdens IF',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '5733',
  'url': 'https://sports.yahoo.com/soccer/teams/djurgårdens-if/'},
 {'abrv': 'FLOR',
  'name': 'Floriana FC',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '4545',
  'url': 'https://sports.yahoo.com/soccer/teams/floriana-fc/'},
 {'abrv': 'FKKR',
  'name': 'FK Krasnodar',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1168',
  'url': 'https://sports.yahoo.com/soccer/teams/fk-krasnodar/'},
 {'abrv': 'OLM',
  'name': 'Marseille',
  'primary_color': '77C5DB',
  'secondary_color': '',
  'team_id': '68',
  'url': 'https://sports.yahoo.com/soccer/teams/marseille/'},
 {'abrv': 'FCAS',
  'name': 'FC Astana',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1323',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-astana/'},
 {'abrv': 'BUDU',
  'name': 'Buducnost Podgorica',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1224',
  'url': 'https://sports.yahoo.com/soccer/teams/buducnost-podgorica/'},
 {'abrv': 'KRR',
  'name': 'KR Reykjavík',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1114',
  'url': 'https://sports.yahoo.com/soccer/teams/kr-reykjavik/'},
 {'abrv': 'CQN',
  'name': "Connah's Quay Nomads",
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2566',
  'url': 'https://sports.yahoo.com/soccer/teams/gap-connahs-quay/'},
 {'abrv': 'CLJ',
  'name': 'Celje',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '3414',
  'url': 'https://sports.yahoo.com/soccer/teams/nk-celje/'},
 {'abrv': 'LINF',
  'name': 'Linfield',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1368',
  'url': 'https://sports.yahoo.com/soccer/teams/linfield/'},
 {'abrv': 'FLO',
  'name': 'Flora',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2502',
  'url': 'https://sports.yahoo.com/soccer/teams/flora/'},
 {'abrv': 'KIK',
  'name': 'KI Klaksvík',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '3316',
  'url': 'https://sports.yahoo.com/soccer/teams/ki-klaksvik/'},
 {'abrv': 'ESC',
  'name': "Inter Club D'Escaldes",
  'primary_color': '',
  'secondary_color': '',
  'team_id': '3327',
  'url': 'https://sports.yahoo.com/soccer/teams/inter-escaldes/'},
 {'abrv': 'SILE',
  'name': 'Sileks',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1755',
  'url': 'https://sports.yahoo.com/soccer/teams/sileks/'},
 {'abrv': 'DGJ',
  'name': 'Drita Gjilan',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '5715',
  'url': 'https://sports.yahoo.com/soccer/teams/drita-gjilan/'},
 {'abrv': 'DINA',
  'name': 'Dinamo Brest',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2812',
  'url': 'https://sports.yahoo.com/soccer/teams/dinamo-brest/'},
 {'abrv': 'FERE',
  'name': 'Ferencvárosi TC',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1305',
  'url': 'https://sports.yahoo.com/soccer/teams/ferencvárosi-tc/'},
 {'abrv': 'TRE',
  'name': 'Tre Fiori',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '5705',
  'url': 'https://sports.yahoo.com/soccer/teams/tre-fiori/'},
 {'abrv': 'DTB',
  'name': 'Dinamo Tbilisi',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1107',
  'url': 'https://sports.yahoo.com/soccer/teams/dinamo-tbilisi/'},
 {'abrv': 'ARM',
  'name': 'Ararat-Armenia',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '4628',
  'url': 'https://sports.yahoo.com/soccer/teams/ararat-armenia/'},
 {'abrv': 'COLL',
  'name': 'Europa',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1318',
  'url': 'https://sports.yahoo.com/soccer/teams/europa/'},
 {'abrv': 'IBB',
  'name': 'Istanbul Basaksehir',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '3419',
  'url': 'https://sports.yahoo.com/soccer/teams/istanbul-basaksehir/'},
 {'abrv': 'KUP',
  'name': 'KuPS Kuopio',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1825',
  'url': 'https://sports.yahoo.com/soccer/teams/kups-kuopio/'},
 {'abrv': 'TIR',
  'name': 'Tirana',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2738',
  'url': 'https://sports.yahoo.com/soccer/teams/tirana/'},
 {'abrv': 'SLP',
  'name': 'Slavia Prague',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2749',
  'url': 'https://sports.yahoo.com/soccer/teams/slavia-prague/'},
 {'abrv': 'DUND',
  'name': 'Dundalk',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1308',
  'url': 'https://sports.yahoo.com/soccer/teams/dundalk/'},
 {'abrv': 'LOK',
  'name': 'Lokomotiva Zagreb',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1803',
  'url': 'https://sports.yahoo.com/soccer/teams/lokomotiva-zagreb/'},
 {'abrv': 'PAO',
  'name': 'PAOK Salonika',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '290',
  'url': 'https://sports.yahoo.com/soccer/teams/paok-salonika/'},
 {'abrv': 'PLZ',
  'name': 'Viktoria Plzen',
  'primary_color': 'CE3030',
  'secondary_color': '',
  'team_id': '171',
  'url': 'https://sports.yahoo.com/soccer/teams/viktoria-plzen/'},
 {'abrv': 'DYK',
  'name': 'Dynamo Kyiv',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '150',
  'url': 'https://sports.yahoo.com/soccer/teams/dynamo-kyiv/'},
 {'abrv': 'LEG',
  'name': 'Legia Warsaw',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '282',
  'url': 'https://sports.yahoo.com/soccer/teams/legia-warsaw/'},
 {'abrv': 'LUD',
  'name': 'Ludogorets Razgrad',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '283',
  'url': 'https://sports.yahoo.com/soccer/teams/ludogorets-razgrad/'},
 {'abrv': 'BES',
  'name': 'Besiktas',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '173',
  'url': 'https://sports.yahoo.com/soccer/teams/besiktas/'},
 {'abrv': 'POR',
  'name': 'FC Porto',
  'primary_color': '2746A1',
  'secondary_color': '',
  'team_id': '152',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-porto/'},
 {'abrv': 'CLUB',
  'name': 'Club Brugge',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '174',
  'url': 'https://sports.yahoo.com/soccer/teams/club-brugge/'},
 {'abrv': 'TIR',
  'name': 'Sheriff Tiraspol',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '295',
  'url': 'https://sports.yahoo.com/soccer/teams/sheriff-tiraspol/'},
 {'abrv': 'LOKO',
  'name': 'Lokomotiv Moscow',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '175',
  'url': 'https://sports.yahoo.com/soccer/teams/lokomotiv-moscow/'},
 {'abrv': 'RAP',
  'name': 'SK Rapid Wien',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '296',
  'url': 'https://sports.yahoo.com/soccer/teams/sk-rapid-wien/'},
 {'abrv': 'OLY',
  'name': 'Olympiakos',
  'primary_color': 'c50000',
  'secondary_color': '',
  'team_id': '154',
  'url': 'https://sports.yahoo.com/soccer/teams/olympiakos/'},
 {'abrv': 'MTA',
  'name': 'Maccabi Tel Aviv',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '286',
  'url': 'https://sports.yahoo.com/soccer/teams/maccabi-tel-aviv/'},
 {'abrv': 'AJA',
  'name': 'Ajax',
  'primary_color': 'C91514',
  'secondary_color': '',
  'team_id': '144',
  'url': 'https://sports.yahoo.com/soccer/teams/ajax/'},
 {'abrv': 'RBS',
  'name': 'FC Red Bull Salzburg',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '276',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-red-bull-salzburg/'},
 {'abrv': 'SHK',
  'name': 'Shakhtar Donetsk',
  'primary_color': 'EC3A1D',
  'secondary_color': '',
  'team_id': '156',
  'url': 'https://sports.yahoo.com/soccer/teams/shakhtar-donetsk/'},
 {'abrv': 'BEF',
  'name': 'Benfica',
  'primary_color': 'EB3B27',
  'secondary_color': '',
  'team_id': '146',
  'url': 'https://sports.yahoo.com/soccer/teams/benfica/'},
 {'abrv': 'AZ',
  'name': 'AZ',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '267',
  'url': 'https://sports.yahoo.com/soccer/teams/az/'},
 {'abrv': 'CEL',
  'name': 'Celtic',
  'primary_color': '018749',
  'secondary_color': '',
  'team_id': '147',
  'url': 'https://sports.yahoo.com/soccer/teams/celtic/'},
 {'abrv': 'CFRC',
  'name': 'CFR Cluj',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '148',
  'url': 'https://sports.yahoo.com/soccer/teams/cfr-cluj/'},
 {'abrv': 'ZNT',
  'name': 'Zenit St Petersburg',
  'primary_color': '0099D1',
  'secondary_color': '',
  'team_id': '159',
  'url': 'https://sports.yahoo.com/soccer/teams/zenit-st-petersburg/'},
 {'abrv': 'BMG',
  'name': 'Borussia Mönchengladbach',
  'primary_color': '7ab92c',
  'secondary_color': '101010',
  'team_id': '105',
  'url': 'https://sports.yahoo.com/soccer/teams/borussia-mönchengladbach/'},
 {'abrv': 'DZG',
  'name': 'Dinamo Zagreb',
  'primary_color': '2C77D1',
  'secondary_color': '',
  'team_id': '149',
  'url': 'https://sports.yahoo.com/soccer/teams/dinamo-zagreb/'},
 {'abrv': 'FKSA',
  'name': 'FK Sarajevo',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1281',
  'url': 'https://sports.yahoo.com/soccer/teams/fk-sarajevo/'},
 {'abrv': 'FCMI',
  'name': 'FC Midtjylland',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1292',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-midtjylland/'},
 {'abrv': 'FOLA',
  'name': 'Fola Esch',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1282',
  'url': 'https://sports.yahoo.com/soccer/teams/fola-esch/'},
 {'abrv': 'FCB',
  'name': 'FC Bayern München',
  'primary_color': 'f00021',
  'secondary_color': 'f3f3f3',
  'team_id': '109',
  'url': 'https://sports.yahoo.com/soccer/teams/fc-bayern-münchen/'},
 {'abrv': 'MOLD',
  'name': 'Molde',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1250',
  'url': 'https://sports.yahoo.com/soccer/teams/molde/'},
 {'abrv': 'PSG',
  'name': 'Paris Saint Germain',
  'primary_color': 'D40506',
  'secondary_color': '',
  'team_id': '73',
  'url': 'https://sports.yahoo.com/soccer/teams/paris-saint-germain/'},
 {'abrv': 'BSCY',
  'name': 'Young Boys',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1350',
  'url': 'https://sports.yahoo.com/soccer/teams/young-boys/'},
 {'abrv': 'REN',
  'name': 'Rennes',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '75',
  'url': 'https://sports.yahoo.com/soccer/teams/rennes/'},
 {'abrv': 'SUD',
  'name': 'Suduva',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2562',
  'url': 'https://sports.yahoo.com/soccer/teams/suduva/'},
 {'abrv': 'SLOV',
  'name': 'Slovan Bratislava',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1121',
  'url': 'https://sports.yahoo.com/soccer/teams/slovan-bratislava/'},
 {'abrv': 'CRV',
  'name': 'Crvena Zvezda',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2496',
  'url': 'https://sports.yahoo.com/soccer/teams/crvena-zvezda/'},
 {'abrv': 'FKQA',
  'name': 'FK Qarabag',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1111',
  'url': 'https://sports.yahoo.com/soccer/teams/fk-qarabag/'},
 {'abrv': 'OMON',
  'name': 'Omonia Nicosia',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1375',
  'url': 'https://sports.yahoo.com/soccer/teams/omonia-nicosia/'},
 {'abrv': 'LDA',
  'name': 'Alajuelense',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1893',
  'url': 'https://sports.yahoo.com/soccer/teams/alajuelense/'},
 {'abrv': 'FOR',
  'name': 'Forge',
  'primary_color': 'dc4405',
  'secondary_color': '53565a',
  'team_id': '6887',
  'url': 'https://sports.yahoo.com/soccer/teams/forge/'},
 {'abrv': 'CDM',
  'name': 'Motagua',
  'primary_color': '003f70',
  'secondary_color': '60a3e4',
  'team_id': '2168',
  'url': 'https://sports.yahoo.com/soccer/teams/motagua/'},
 {'abrv': 'SFR',
  'name': 'San Francisco',
  'primary_color': 'dd1313',
  'secondary_color': '0c0c0c',
  'team_id': '2169',
  'url': 'https://sports.yahoo.com/soccer/teams/san-francisco/'},
 {'abrv': 'CDF',
  'name': 'FAS',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1897',
  'url': 'https://sports.yahoo.com/soccer/teams/cd-fas/'},
 {'abrv': 'OLI',
  'name': 'Olimpia de Tegucigalpa',
  'primary_color': 'd50b20',
  'secondary_color': '3344a3',
  'team_id': '1899',
  'url': 'https://sports.yahoo.com/soccer/teams/olimpia-de-tegucigalpa/'},
 {'abrv': 'WHO',
  'name': 'Waterhouse',
  'primary_color': '6db8ec',
  'secondary_color': 'ffe500',
  'team_id': '1910',
  'url': 'https://sports.yahoo.com/soccer/teams/waterhouse-fc/'},
 {'abrv': 'ALZ',
  'name': 'Alianza San Salvador',
  'primary_color': '1c2581',
  'secondary_color': '2e86c3',
  'team_id': '2516',
  'url': 'https://sports.yahoo.com/soccer/teams/alianza/'},
 {'abrv': 'COM',
  'name': 'Comunicaciones',
  'primary_color': '0098c0',
  'secondary_color': '053e6b',
  'team_id': '1900',
  'url': 'https://sports.yahoo.com/soccer/teams/comunicaciones/'},
 {'abrv': 'AG',
  'name': 'Antigua GFC',
  'primary_color': '72c400',
  'secondary_color': '003f0e',
  'team_id': '2517',
  'url': 'https://sports.yahoo.com/soccer/teams/antigua-gfc/'},
 {'abrv': 'HRD',
  'name': 'Herediano',
  'primary_color': 'f7e600',
  'secondary_color': 'e80c15',
  'team_id': '1902',
  'url': 'https://sports.yahoo.com/soccer/teams/herediano/'},
 {'abrv': 'MCP',
  'name': 'Municipal de Guatemala',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '1904',
  'url': 'https://sports.yahoo.com/soccer/teams/municipal/'},
 {'abrv': 'ESI',
  'name': 'Real Estelí',
  'primary_color': 'd92319',
  'secondary_color': 'ffffff',
  'team_id': '1907',
  'url': 'https://sports.yahoo.com/soccer/teams/real-estelí/'},
 {'abrv': 'SPR',
  'name': 'Saprissa',
  'primary_color': '7a003c',
  'secondary_color': 'e2e2e2',
  'team_id': '1908',
  'url': 'https://sports.yahoo.com/soccer/teams/saprissa/'},
 {'abrv': 'TAU',
  'name': 'Tauro FC',
  'primary_color': '121212',
  'secondary_color': 'b09442',
  'team_id': '1909',
  'url': 'https://sports.yahoo.com/soccer/teams/tauro-fc/'},
 {'abrv': 'ARC',
  'name': 'Arcahaie',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '8397',
  'url': 'https://sports.yahoo.com/soccer/teams/arcahaie/'},
 {'abrv': 'CAI',
  'name': 'Club Atlético Independiente',
  'primary_color': 'fbe200',
  'secondary_color': '000000',
  'team_id': '6241',
  'url': 'https://sports.yahoo.com/soccer/teams/independiente-la-chorrera/'},
 {'abrv': 'MNL',
  'name': 'Municipal Limeño',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '8398',
  'url': 'https://sports.yahoo.com/soccer/teams/municipal-limeÃ±o/'},
 {'abrv': 'MAN',
  'name': 'Managua',
  'primary_color': '434ea2',
  'secondary_color': '243176',
  'team_id': '6891',
  'url': 'https://sports.yahoo.com/soccer/teams/managua/'},
 {'abrv': 'MAR',
  'name': 'Marathón',
  'primary_color': '00984a',
  'secondary_color': 'ed1c24',
  'team_id': '6242',
  'url': 'https://sports.yahoo.com/soccer/teams/marathón/'},
 {'abrv': 'CIB',
  'name': 'Cibao FC',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '5168',
  'url': 'https://sports.yahoo.com/soccer/teams/cibao-fc/'},
 {'abrv': 'VER',
  'name': 'Verdes',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '2166',
  'url': 'https://sports.yahoo.com/soccer/teams/hankook-real-verdes-united/'},
 {'abrv': 'NSH',
  'name': 'Nashville SC',
  'primary_color': '1f1646',
  'secondary_color': 'fffd24',
  'team_id': '7262',
  'url': 'https://sports.yahoo.com/soccer/teams/nashville-sc/'},
 {'abrv': 'POR',
  'name': 'Portland Thorns FC',
  'primary_color': '215732',
  'secondary_color': 'af272f',
  'team_id': '6634',
  'url': 'https://sports.yahoo.com/soccer/teams/portland-thorns/'},
 {'abrv': 'WAS',
  'name': 'Washington Spirit',
  'primary_color': 'ba0c2f',
  'secondary_color': '081f2c',
  'team_id': '6635',
  'url': 'https://sports.yahoo.com/soccer/teams/washington-spirit/'},
 {'abrv': 'NJ',
  'name': 'Sky Blue FC',
  'primary_color': 'fe5000',
  'secondary_color': '00205b',
  'team_id': '6636',
  'url': 'https://sports.yahoo.com/soccer/teams/sky-blue/'},
 {'abrv': 'UTA',
  'name': 'Utah Royals FC',
  'primary_color': '13294b',
  'secondary_color': '9d2235',
  'team_id': '6637',
  'url': 'https://sports.yahoo.com/soccer/teams/utah-royals/'},
 {'abrv': 'HOU',
  'name': 'Houston Dash',
  'primary_color': 'e57200',
  'secondary_color': '8bb8e8',
  'team_id': '6629',
  'url': 'https://sports.yahoo.com/soccer/teams/houston-dash/'},
 {'abrv': 'SEA',
  'name': 'Reign FC',
  'primary_color': '7c878e',
  'secondary_color': '1D252D',
  'team_id': '6630',
  'url': 'https://sports.yahoo.com/soccer/teams/reign/'},
 {'abrv': 'NC',
  'name': 'North Carolina Courage',
  'primary_color': 'a50034',
  'secondary_color': '01426a',
  'team_id': '6631',
  'url': 'https://sports.yahoo.com/soccer/teams/north-carolina-courage/'},
 {'abrv': 'CHI',
  'name': 'Chicago Red Stars',
  'primary_color': '41b6e6',
  'secondary_color': 'c8102e',
  'team_id': '6632',
  'url': 'https://sports.yahoo.com/soccer/teams/chicago-red-stars/'},
 {'abrv': 'ORL',
  'name': 'Orlando Pride',
  'primary_color': '5f259f',
  'secondary_color': '00a9e0',
  'team_id': '6633',
  'url': 'https://sports.yahoo.com/soccer/teams/orlando-pride/'},
 {'abrv': 'ELC',
  'name': 'Elche',
  'primary_color': '006039',
  'secondary_color': '',
  'team_id': '26',
  'url': 'https://sports.yahoo.com/soccer/teams/elche/'},
 {'abrv': 'CAD',
  'name': 'Cádiz',
  'primary_color': '052057',
  'secondary_color': 'f1c421',
  'team_id': '1390',
  'url': 'https://sports.yahoo.com/soccer/teams/cádiz/'},
 {'abrv': 'HUE',
  'name': 'Huesca',
  'primary_color': '273480',
  'secondary_color': 'b01630',
  'team_id': '735',
  'url': 'https://sports.yahoo.com/soccer/teams/huesca/'},
 {'abrv': 'BENE',
  'name': 'Benevento',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '830',
  'url': 'https://sports.yahoo.com/soccer/teams/benevento/'},
 {'abrv': 'CROT',
  'name': 'Crotone',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '643',
  'url': 'https://sports.yahoo.com/soccer/teams/crotone/'},
 {'abrv': 'SPEZ',
  'name': 'Spezia',
  'primary_color': '',
  'secondary_color': '',
  'team_id': '655',
  'url': 'https://sports.yahoo.com/soccer/teams/spezia/'},
 {'abrv': 'KOE',
  'name': '1. FC Köln',
  'primary_color': 'f2f2f2',
  'secondary_color': 'eb040d',
  'team_id': '693',
  'url': 'https://sports.yahoo.com/soccer/teams/1-fc-köln/'},
 {'abrv': 'DSC',
  'name': 'DSC Arminia Bielefeld',
  'primary_color': '004e95',
  'secondary_color': '101010',
  'team_id': '695',
  'url': 'https://sports.yahoo.com/soccer/teams/dsc-arminia-bielefeld/'},
 {'abrv': 'VFB',
  'name': 'VfB Stuttgart',
  'primary_color': 'f3f3f3',
  'secondary_color': 'f60000',
  'team_id': '116',
  'url': 'https://sports.yahoo.com/soccer/teams/vfb-stuttgart/'}]


stadiums = [{'stadium_id': '24', 'title': 'BayArena'},
 {'stadium_id': '353', 'title': 'Spotland'},
 {'stadium_id': '158', 'title': 'Iberostar Estadi'},
 {'stadium_id': '127', 'title': 'Molineux Stadium'},
 {'stadium_id': '1687', 'title': 'Estadio Municipal, Marbella'},
 {'stadium_id': '28', 'title': 'Commerzbank Arena'},
 {'stadium_id': '74513', 'title': 'Wanda Metropolitano'},
 {'stadium_id': '458', 'title': 'An der Alten Försterei'},
 {'stadium_id': '92', 'title': "Atleti Azzurri d'Italia"},
 {'stadium_id': '457', 'title': 'RheinEnergieStadion'},
 {'stadium_id': '31', 'title': 'VELTINS-Arena'},
 {'stadium_id': '85', 'title': 'Olimpico'},
 {'stadium_id': '486', 'title': 'Ipurua'},
 {'stadium_id': '167', 'title': 'King Power Stadium'},
 {'stadium_id': '613', 'title': 'Via Del Mare'},
 {'stadium_id': '22', 'title': 'Coface Arena'},
 {'stadium_id': '74062', 'title': 'Saint Petersburg Stadium'},
 {'stadium_id': '113', 'title': "St. Mary's Stadium"},
 {'stadium_id': '93', 'title': "Renato Dall'Ara"},
 {'stadium_id': '88', 'title': 'Ennio Tardini'},
 {'stadium_id': '84', 'title': 'Giuseppe Meazza'},
 {'stadium_id': '106', 'title': 'Selhurst Park'},
 {'stadium_id': '96', 'title': 'Friuli'},
 {'stadium_id': '49', 'title': 'Coliseum Alfonso Pérez'},
 {'stadium_id': '1', 'title': 'Stade de la Mosson'},
 {'stadium_id': '51', 'title': 'Cornellá - El Prat'},
 {'stadium_id': '407', 'title': 'Mario Rigamonti'},
 {'stadium_id': '74980', 'title': 'Tottenham Hotspur Stadium'},
 {'stadium_id': '55497', 'title': 'Paolo Mazza'},
 {'stadium_id': '239', 'title': 'Stade de Sclessin'},
 {'stadium_id': '91', 'title': 'Juventus Stadium'},
 {'stadium_id': '90', 'title': 'Artemio Franchi'},
 {'stadium_id': '38', 'title': 'Volkswagen Arena'},
 {'stadium_id': '462', 'title': 'ESPRIT arena'},
 {'stadium_id': '98', 'title': 'Emirates Stadium'},
 {'stadium_id': '223', 'title': 'Goldsands Stadium'},
 {'stadium_id': '169', 'title': 'Hillsborough'},
 {'stadium_id': '39', 'title': 'Anoeta'},
 {'stadium_id': '224', 'title': 'Amex Stadium'},
 {'stadium_id': '79', 'title': 'Red Bull Arena'},
 {'stadium_id': '41', 'title': 'Mestalla'},
 {'stadium_id': '74434', 'title': 'Sardegna Arena'},
 {'stadium_id': '42', 'title': 'Camp Nou'},
 {'stadium_id': '112', 'title': "St. James' Park"},
 {'stadium_id': '47', 'title': 'Balaídos'},
 {'stadium_id': '36', 'title': 'Weserstadion'},
 {'stadium_id': '220', 'title': 'Lokomotiv Stadium, Moscow'},
 {'stadium_id': '74510', 'title': 'Hermann-Neuberger-Stadion'},
 {'stadium_id': '124', 'title': 'Turf Moor'},
 {'stadium_id': '821', 'title': 'Giuseppe Moccagatta'},
 {'stadium_id': '81', 'title': 'Luigi Ferraris'},
 {'stadium_id': '25', 'title': 'Signal Iduna Park'},
 {'stadium_id': '117', 'title': 'Old Trafford'},
 {'stadium_id': '9613', 'title': 'Arena Lviv'},
 {'stadium_id': '44', 'title': 'Santiago Bernabéu'},
 {'stadium_id': '103', 'title': 'The Hawthorns'},
 {'stadium_id': '56', 'title': 'Benito Villamarín'},
 {'stadium_id': '34', 'title': 'Olympiastadion'},
 {'stadium_id': '99', 'title': 'Anfield'},
 {'stadium_id': '65', 'title': 'Providence Park'},
 {'stadium_id': '172', 'title': 'Bramall Lane'},
 {'stadium_id': '54', 'title': 'Ciutat de València'},
 {'stadium_id': '40', 'title': 'José Zorrilla'},
 {'stadium_id': '687', 'title': 'Olympic Stadium'},
 {'stadium_id': '107', 'title': 'Etihad Stadium'},
 {'stadium_id': '29', 'title': 'WWK Arena'},
 {'stadium_id': '43', 'title': 'El Sadar'},
 {'stadium_id': '100', 'title': 'Carrow Road'},
 {'stadium_id': '87', 'title': 'San Paolo'},
 {'stadium_id': '35', 'title': 'MAGE SOLAR Stadion'},
 {'stadium_id': '110', 'title': 'Craven Cottage'},
 {'stadium_id': '312', 'title': 'Deepdale'},
 {'stadium_id': '598', 'title': 'ERDGAS Sportpark'},
 {'stadium_id': '109', 'title': 'Goodison Park'},
 {'stadium_id': '470', 'title': 'Mendizorroza'},
 {'stadium_id': '30', 'title': 'Allianz Arena'},
 {'stadium_id': '35922', 'title': 'UPC-Arena'},
 {'stadium_id': '58', 'title': 'San Mamés'},
 {'stadium_id': '499', 'title': 'Butarque'},
 {'stadium_id': '503', 'title': 'Municipal de Anduva'},
 {'stadium_id': '331', 'title': 'Pirelli Stadium'},
 {'stadium_id': '50', 'title': 'Martínez Valero'},
 {'stadium_id': '23', 'title': 'WIRSOL Rhein-Neckar-Arena'},
 {'stadium_id': '57', 'title': 'Estadio Los Cármenes'},
 {'stadium_id': '73659', 'title': 'Nuevo Matapiñonera'},
 {'stadium_id': '108', 'title': 'Villa Park'},
 {'stadium_id': '105', 'title': 'Stamford Bridge'},
 {'stadium_id': '73253', 'title': 'Las Gaunas'},
 {'stadium_id': '161', 'title': 'La Romareda'},
 {'stadium_id': '52', 'title': 'El Madrigal'},
 {'stadium_id': '464', 'title': 'Benteler-Arena'},
 {'stadium_id': '317', 'title': 'Weston Homes Community Stadium'},
 {'stadium_id': '351', 'title': 'The Kassam Stadium'},
 {'stadium_id': '74894', 'title': 'Banc of California Stadium'},
 {'stadium_id': '75154', 'title': 'Anexo Estadio HelmÃ¡ntico'},
 {'stadium_id': '82', 'title': "Marc'Antonio Bentegodi"},
 {'stadium_id': '308', 'title': 'Alexandra Stadium'},
 {'stadium_id': '48', 'title': 'Campo de Fútbol de Vallecas'},
 {'stadium_id': '175', 'title': 'Vicarage Road'},
 {'stadium_id': '146', 'title': 'Dinamo Stadion, Minsk'},
 {'stadium_id': '151', 'title': 'Eden Arena'},
 {'stadium_id': '74895', 'title': 'Audi Field'},
 {'stadium_id': '313', 'title': 'New Meadow'},
 {'stadium_id': '45', 'title': 'Ramón Sánchez Pizjuán'},
 {'stadium_id': '74570', 'title': 'Municipal de Badalona'},
 {'stadium_id': '149', 'title': 'Neo GSP Stadium'},
 {'stadium_id': '258', 'title': 'Ludogorets Arena'},
 {'stadium_id': '182', 'title': 'Jan Breydel'},
 {'stadium_id': '35293', 'title': 'Ghelamco Arena'},
 {'stadium_id': '72', 'title': 'Stade Olympique (Montreal)'},
 {'stadium_id': '74583', 'title': 'Príncipe Felipe'},
 {'stadium_id': '95', 'title': 'Città del Tricolore'},
 {'stadium_id': '521', 'title': False},
 {'stadium_id': '491', 'title': 'El Mazo'},
 {'stadium_id': '138', 'title': 'Estadio do Dragao'},
 {'stadium_id': '27929', 'title': 'Avaya Stadium'},
 {'stadium_id': '26', 'title': 'Borussia-Park'},
 {'stadium_id': '527', 'title': 'Alfredo Di Stéfano Stadium'},
 {'stadium_id': '60', 'title': 'BC Place'},
 {'stadium_id': '230', 'title': 'Red Bull Arena Salzburg'},
 {'stadium_id': '159', 'title': 'Nueva Condomina'},
 {'stadium_id': '89', 'title': 'Olimpico di Torino'},
 {'stadium_id': '496', 'title': 'Francisco Artés Carrasco'},
 {'stadium_id': '73507', 'title': 'Vodafone Arena'},
 {'stadium_id': '350', 'title': 'Rodney Parade'},
 {'stadium_id': '162', 'title': 'Nuevo Colombino'},
 {'stadium_id': '132', 'title': 'Estadio da Luz'},
 {'stadium_id': '134', 'title': 'Stadionul Dr. Constantin Radulescu'},
 {'stadium_id': '227', 'title': 'The New Den'},
 {'stadium_id': '15834', 'title': 'Estadio Ruta de la Plata'},
 {'stadium_id': '140', 'title': 'Karaiskaki Stadium'},
 {'stadium_id': '73879', 'title': 'King Abdullah Sports City, Jeddah'},
 {'stadium_id': '5193', 'title': 'Las Llanas'},
 {'stadium_id': '144', 'title': 'Estádio Municipal de Braga'},
 {'stadium_id': '38641', 'title': 'Reino de León'},
 {'stadium_id': '74098', 'title': 'Orlando City Stadium'},
 {'stadium_id': '74', 'title': 'Rio Tinto Stadium'},
 {'stadium_id': '73728', 'title': 'Slavutych Arena'},
 {'stadium_id': '651', 'title': 'A. Le Coq Arena'},
 {'stadium_id': '799', 'title': 'Swedbank Stadion'},
 {'stadium_id': '253', 'title': 'Astana Arena'},
 {'stadium_id': '152', 'title': 'St Jakob-Park'},
 {'stadium_id': '1789', 'title': 'Nagyerdei Stadium'},
 {'stadium_id': '664', 'title': 'Stade Josy Barthel'},
 {'stadium_id': '75131', 'title': 'Senol Güne&#351; Spor Kompleksi'},
 {'stadium_id': '4', 'title': 'Grand Stade Lille Métropole'},
 {'stadium_id': '64', 'title': 'CenturyLink Field'},
 {'stadium_id': '73791', 'title': 'Arena CSKA'},
 {'stadium_id': '73657', 'title': 'La Planilla'},
 {'stadium_id': '184', 'title': 'Ibrox Stadium'},
 {'stadium_id': '55546', 'title': 'Álvarez Claro'},
 {'stadium_id': '73429', 'title': 'Stade des Lumières'},
 {'stadium_id': '148', 'title': 'Wembley'},
 {'stadium_id': '135', 'title': 'Maksimir'},
 {'stadium_id': '7', 'title': 'Stade de la Route-de-Lorient'},
 {'stadium_id': '240', 'title': 'Estádio D. Alfonso Henriques'},
 {'stadium_id': '62', 'title': 'FC Dallas Stadium'},
 {'stadium_id': '307', 'title': 'Broadfield Stadium'},
 {'stadium_id': '743', 'title': 'FLYERALARM Arena'},
 {'stadium_id': '20', 'title': 'Parc des Princes'},
 {'stadium_id': '125', 'title': 'Fratton Park'},
 {'stadium_id': '73', 'title': 'Red Bull Arena (USA)'},
 {'stadium_id': '679', 'title': 'Crvena Zvezda Stadium'},
 {'stadium_id': '549', 'title': 'Osnatel Arena'},
 {'stadium_id': '309', 'title': 'Priestfield Stadium'},
 {'stadium_id': '362', 'title': 'Sincil Bank'},
 {'stadium_id': '4404', 'title': 'Stjörnuvöllur'},
 {'stadium_id': '55548', 'title': 'Romano'},
 {'stadium_id': '500', 'title': "Camp d'Esports"},
 {'stadium_id': '61', 'title': 'StubHub Center'},
 {'stadium_id': '73756', 'title': 'Krasnodar Stadium'},
 {'stadium_id': '74460', 'title': 'Friedensstadion'},
 {'stadium_id': '217', 'title': 'Schauinsland-Reisen-Arena'},
 {'stadium_id': '111', 'title': 'The KC Stadium'},
 {'stadium_id': '4483', 'title': 'Metalist Stadium'},
 {'stadium_id': '76', 'title': 'Gillette Stadium'},
 {'stadium_id': '63', 'title': 'BBVA Compass Stadium'},
 {'stadium_id': '150', 'title': 'Cristal Arena'},
 {'stadium_id': '38648', 'title': 'Nissan Stadium'},
 {'stadium_id': '513', 'title': 'Nuevo Estadio de La Victoria'},
 {'stadium_id': '460', 'title': 'Audi Sportpark'},
 {'stadium_id': '77', 'title': 'BMO Field'},
 {'stadium_id': '165', 'title': 'Pride Park Stadium'},
 {'stadium_id': '71', 'title': 'Columbus Crew Stadium'},
 {'stadium_id': '69', 'title': "Dick's Sporting Goods Park"},
 {'stadium_id': '75', 'title': 'Sporting Park'},
 {'stadium_id': '620', 'title': 'Renato Curi'},
 {'stadium_id': '276', 'title': 'Tehelne Pole Stadium'},
 {'stadium_id': '16', 'title': 'Stade Geoffroy-Guichard'},
 {'stadium_id': '645', 'title': 'Tofik Bakhramov Stadium'},
 {'stadium_id': '411', 'title': 'Ezio Scida'},
 {'stadium_id': '26658', 'title': 'Stade de la Meinau'},
 {'stadium_id': '323', 'title': 'The Memorial Stadium'},
 {'stadium_id': '316', 'title': 'Griffin Park'},
 {'stadium_id': '519', 'title': 'El Carmen'},
 {'stadium_id': '322', 'title': 'Prenton Park'},
 {'stadium_id': '383', 'title': 'Kenilworth Road'},
 {'stadium_id': '215', 'title': 'SchücoArena'},
 {'stadium_id': '75113', 'title': 'Alfonso Murube'},
 {'stadium_id': '319', 'title': 'Stadium:mk'},
 {'stadium_id': '495', 'title': 'Nou Municipal de Hospitalet'},
 {'stadium_id': '130', 'title': 'Amsterdam Arena'},
 {'stadium_id': '456', 'title': 'Fritz-Walter-Stadion'},
 {'stadium_id': '19784', 'title': 'Groupama Arena'},
 {'stadium_id': '4385', 'title': 'Seaview'},
 {'stadium_id': '4447', 'title': 'Swissporarena'},
 {'stadium_id': '73236', 'title': 'La Florida'},
 {'stadium_id': '129', 'title': 'Madejski Stadium'},
 {'stadium_id': '490', 'title': 'Municipal Montilivi'},
 {'stadium_id': '662', 'title': 'Rheinpark Stadion'},
 {'stadium_id': '123', 'title': 'Riverside Stadium'},
 {'stadium_id': '621', 'title': 'Arena Garibaldi Romeo Anconetani'},
 {'stadium_id': '139', 'title': 'Türk Telekom Arena'},
 {'stadium_id': '461', 'title': 'Millerntor-Stadion'},
 {'stadium_id': '73405', 'title': 'Basaksehir Fatih Terim Stadium'},
 {'stadium_id': '74691', 'title': 'Mercedes-Benz Stadium'},
 {'stadium_id': '644', 'title': 'Hanrapetakan Stadium'},
 {'stadium_id': '75037', 'title': 'Häcker-Wiehenstadion'},
 {'stadium_id': '183', 'title': 'FK Partizan Stadium'},
 {'stadium_id': '761', 'title': 'Kyocera Stadion'},
 {'stadium_id': '157', 'title': 'Riazor'},
 {'stadium_id': '133', 'title': 'Celtic Park'},
 {'stadium_id': '19301', 'title': 'Linzer Stadion'},
 {'stadium_id': '529', 'title': 'MDCC-Arena'},
 {'stadium_id': '73502', 'title': "Camp de Futbol Municipal d'Encamp"}]


class SOCCERDB(DB):

    _abrv = "soccer"

    _schema = ("""
                    CREATE TABLE games (
                        game_id INT PRIMARY KEY,
                        home_id INT NOT NULL,
                        away_id INT NOT NULL,
                        winner_id INT NOT NULL,
                        loser_id INT NOT NULL,
                        stadium_id INT NOT NULL,
                        league_id TEXT NOT NULL,
                        game_type TEXT NOT NULL,
                        season INT NOT NULL,
                        week INT NOT NULL,
                        game_time TEXT NOT NULL,
                        outcome TEXT NOT NULL,
                        FOREIGN KEY (home_id) REFERENCES teams (team_id),
                        FOREIGN KEY (away_id) REFERENCES teams (team_id),
                        FOREIGN KEY (winner_id) REFERENCES teams (team_id),
                        FOREIGN KEY (loser_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stadium_id) REFERENCES stadiums (stadium_id),
                        FOREIGN KEY (league_id) REFERENCES leagues (league_id)

                    )
                """,
                """
                    CREATE INDEX idx_season_date ON games (season, week, league_id)
                """,
                """
                    CREATE TABLE leagues (
                        league_id TEXT PRIMARY KEY,
                        title TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE players (
                        player_id INT PRIMARY KEY,
                        first_name TEXT,
                        last_name TEXT,
                        pos_id INT,
                        FOREIGN KEY (pos_id) REFERENCES position_types (pos_id)
                    )
                """,
                """
                    CREATE INDEX idx_names ON players (last_name, first_name)
                """,
                """
                    CREATE TABLE teams (
                        team_id INT PRIMARY KEY,
                        abrv TEXT,
                        name TEXT,
                        primary_color TEXT,
                        secondary_color TEXT,
                        url TEXT
                    )
                """,
                """
                    CREATE TABLE stadiums (
                        stadium_id INT PRIMARY KEY,
                        title TEXT
                    )
                """,
                """
                    CREATE TABLE lineups (
                        lineup_id INT PRIMARY KEY,
                        game_id INT NOT NULL,
                        player_id INT NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        starter INT NOT NULL,
                        active INT NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (player_id) REFERENCES players (player_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id)
                    )
                """,
                """
                    CREATE TABLE player_stats (
                        player_id INT NOT NULL,
                        game_id INT NOT NULL,
                        team_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        stat_id INT NOT NULL,
                        value INT NOT NULl,
                        PRIMARY KEY (player_id, game_id, stat_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stat_id) REFERENCES stat_types (stat_id)
                    )
                """,
                """
                    CREATE TABLE team_stats (
                        team_id INT NOT NULL,
                        game_id INT NOT NULL,
                        opp_id INT NOT NULL,
                        stat_id INT NOT NULL,
                        value REAL,
                        PRIMARY KEY (team_id, game_id, stat_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id),
                        FOREIGN KEY (opp_id) REFERENCES teams (team_id),
                        FOREIGN KEY (stat_id) REFERENCES stat_types (stat_id)
                    )
                """,
                """
                    CREATE INDEX idx_opp_stats ON team_stats (opp_id, game_id)
                """,
                """
                    CREATE TABLE position_types (
                        pos_id INT PRIMARY KEY,
                        title TEXT NOT NULL,
                        abrv TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE stat_types (
                        stat_id INT PRIMARY KEY,
                        title TEXT NOT NULL,
                        abrv TEXT NOT NULL
                    )
                """,
                """
                    CREATE TABLE game_lines (
                        team_id INT NOT NULL,
                        game_id INT NOT NULL,
                        spread REAL NOT NULL,
                        line INT NOT NULL,
                        money INT NOT NULL,
                        result INT NOT NULL,
                        spread_outcome INT NOT NULL,
                        money_outcome INT NOT NULL,
                        PRIMARY KEY (team_id, game_id),
                        FOREIGN KEY (team_id) REFERENCES teams (team_id),
                        FOREIGN KEY (game_id) REFERENCES games (game_id)
                    )
                """,
                """
                    CREATE TABLE over_unders (
                        game_id INT PRIMARY Key,
                        ou REAL NOT NULL,
                        over_line REAL NOT NULL,
                        under_line REAL NOT NULL,
                        total INT NOT NULL,
                        outcome INT NOT NULL,
                        FOREIGN KEY (game_id) REFERENCES games (game_id)
                    )
                """
                )

    def __init__(self):
        super().__init__()


    def insertGame(self, gameInfo):
        # pprint(gameInfo)
        gameId = yId(gameInfo["gameData"]["gameid"])
        homeId = yId(gameInfo["gameData"]["home_team_id"])
        awayId = yId(gameInfo["gameData"]["away_team_id"])
        if not gameInfo["gameData"]["winning_team_id"]:
            winnerId = -1; loserId = -1
        else:
            winnerId = yId(gameInfo["gameData"]["winning_team_id"])
            loserId = awayId if winnerId == homeId else homeId
        stadiumId = gameInfo["gameData"]["stadium_id"]
        leagueId = yId(gameInfo["gameData"]["subleague"])
        gameType = yId(gameInfo["gameData"]["season_phase_id"])
        season = gameInfo["gameData"]["season"]
        week = gameInfo["gameData"]["week_number"]
        gameTime = gameInfo["gameData"]["start_time"]
        outcome = yId(gameInfo["gameData"]["outcome_type"])
        self.insert("games", values=(gameId, homeId, awayId, winnerId, loserId,
                                        stadiumId, leagueId, gameType, season,
                                        week, gameTime, outcome))

        # pprint(gameInfo)
        players = {}

        for team in ("home", "away"):
            if team == "home":
                teamId = homeId; oppId = awayId
            else:
                teamId = awayId; oppId = homeId

            try:
                for key, value in [(key, value) for key, value in gameInfo["gameData"]["lineups"]["{}_lineup".format(team)].items() if key not in ('all', 'formation')]:
                    active = 1; starter = 1;
                    for playerId, player in value.items():
                        playerId = yId(playerId)
                        players[playerId] = (teamId, oppId)
                        if key == '15':
                            starter = 0
                            if not player.get("lineup_detailed", None):
                                active = 0

                        self.insert("lineups", values=(None, gameId, playerId, teamId, oppId, starter, active))
            except AttributeError:
                pass

        try:
            for playerId, value in gameInfo["statsData"]["playerStats"].items():
                playerId = yId(playerId)
                teamId, oppId = players[playerId]
                for statId, stat in value["soccer.stat_variation.2"].items():
                    statId = yId(statId)
                    self.insert("player_stats", values=(playerId, gameId, teamId, oppId, statId, stat))
        except KeyError:
            pass

        try:

            for teamId, value in gameInfo["statsData"]["teamStatsByGameId"]["soccer.g.{}".format(gameId)].items():
                teamId = yId(teamId)
                oppId = awayId if teamId == homeId else homeId
                for statId, stat in value["soccer.stat_variation.2"].items():
                    statId = yId(statId)
                    if "%" in stat:
                        stat = "."+stat[:-1]
                    self.insert("team_stats", values=(teamId, gameId, oppId, statId, stat))

            self.insert("team_stats", values=(homeId, gameId, awayId, 400, gameInfo["gameData"]["lineups"]["home_lineup"]["formation"]))
            self.insert("team_stats", values=(awayId, gameId, homeId, 400, gameInfo["gameData"]["lineups"]["away_lineup"]["formation"]))
        except KeyError:
            pass


    def seed(self):

        for position in positions:
            self.insert("position_types", info=position)

        for team in teams:
            self.insert("teams", info=team)
        self.insert("teams", values=(-1,None,None,None,None,None))

        for stadium in stadiums:
            self.insert("stadiums", info=stadium)

        for league in leagues:
            self.insert("leagues", info=league)

        for stat in statTypes:
            self.insert("stat_types", info=stat)

        playerPath = "/home/ededub/Yahoo/soccer/players/"
        gamePath = "/home/ededub/Yahoo/soccer/2019/"

        for fileName in [playerPath+fileName for fileName in os.listdir(playerPath)]:
            with open(fileName) as fileIn:
                info = json.load(fileIn)
            self.insert("players", info=info)

        for fileName in [gamePath+fileName for fileName in os.listdir(gamePath)]:
            print(fileName)
            with open(fileName) as fileIn:
                info = json.load(fileIn)
            self.insertGame(info)

        # self.insertPlayers()
        # self.insertBoxScores()


        self.commit()
